version: '3'

services:

  elasticsearch:
#    image: "elasticsearch:8.10.3"
#    image: "elasticsearch:7.17.7"
    image: "elasticsearch:7.13.3"
    hostname: $HOSTNAME
    container_name: elasticsearch
    environment:
      - cluster.name=mps-dev
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2560m -Xmx2560m -DLog4j2.formatMsgNoLookups=true"
      - xpack.security.enabled=false
#      - ELASTIC_PASSWORD=Wzx789E
#      - xpack.monitoring.enabled=true
#      - xpack.monitoring.collection.enabled=true
#      - xpack.ml.enabled=false
#      - xpack.graph.enabled=false
#      - xpack.watcher.enabled=false
#      - xpack.security.audit.enabled=true
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - indices.analysis.hunspell.dictionary.en_US.ignore_case=true
      - indices.analysis.hunspell.dictionary.ru_RU.ignore_case=true
#      - path.repo=/opt/elasticsearch/repo
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
#        soft: 65536
#        hard: 65536
        soft: 500000
        hard: 500000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "app,es_index_name"
    labels:
      app: "elastic"
      product_id: "cos-dev-elasticsearch"
    volumes:
      - "./data:/usr/share/elasticsearch/data"
      - ./hunspell:/usr/share/elasticsearch/config/hunspell
#      - "/data/elk/backup:/opt/elasticsearch/repo"
    network_mode: host
#    ports:
#      - 9200:9200
#      - 9300:9300
    restart: always
#    networks:
#     - backend

#networks:
#  backend:
#    driver: bridge
