version: "3"
services:

  nginx:
    image: "nginx:1.20.1"
    container_name: nginx-kc
    hostname: $HOSTNAME
    restart: unless-stopped
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./cert/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./cert/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./config/conf.d:/etc/nginx/conf.d/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/:/var/log/nginx/
    extra_hosts:
     - "dev-kc:10.80."
    network_mode: host
    logging: 
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        labels: "product_id,index_period"
    labels:
      product_id: "fermcard-wcms-nginx-dev-dtln"
#      index_period: "day"
#      filebeat.enable: "true"

