- name: Deploy Logstash
  hosts: logstash
  gather_facts: true
  vars:
    # up/down/restart/none
    dc: none

  roles:
    - role: preparatory_tasks
      tags: preparatory_tasks
    - role: deploy_logstash
      tags: deploy_logstash
