version: '2'
services:

  web:
    image: ansible/awx:14.1.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "/opt/.awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/opt/.awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/opt/.awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/opt/.awx/awxcompose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/opt/.awx/awxcompose/redis_socket:/var/run/redis/:rw"
      - "/opt/awx/projects:/var/lib/awx/projects:rw"
      - "/var/lib/awx/custom-venv/python36/:/var/lib/awx/custom-venv/python36/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx:14.1.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "/opt/.awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/opt/.awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/opt/.awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/opt/.awx/awxcompose/redis_socket:/var/run/redis/:rw"
      - "/opt/awx/projects:/var/lib/awx/projects:rw"
      - "/var/lib/awx/custom-venv/python36/:/var/lib/awx/custom-venv/python36/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "/opt/.awx/awxcompose/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "/opt/.awx/awxcompose/redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - /opt/.awx/pgdocker/10/data/:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      http_proxy: 
      https_proxy: 
      no_proxy: 


volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
