---
- name: Clear local temporary directory for certificates
  local_action:
    module: file
    path: /tmp/nodecerts
    state: absent
  run_once: true
  tags: tmp_folder

- name: Create local temporary directory for certificates generation
  local_action:
    module: file
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.user }}"
  with_items:
    - { path: '/tmp/nodecerts', group: 'docker', user: '{{ svc_user }}', mode: '0775' }
    - { path: '/tmp/nodecerts/tools', group: 'docker', user: '{{ svc_user }}', mode: '0775' }
    - { path: '/tmp/nodecerts/config', group: 'docker', user: '{{ svc_user }}', mode: '0775' }
  run_once: true
  tags: tmp_folder

# if doesnt work just comment 'run_once: true' lines

- name: Copy certificates generation tool
  local_action:
    module: copy
    src: 'search-guard-tlstool-1.5.zip'
    dest: /tmp/nodecerts/search-guard-tlstool.zip
  run_once: true
  tags: tlstool

- name: Extract the certificates generation tool
  local_action: 
    module: unarchive
    src: /tmp/nodecerts/search-guard-tlstool.zip
    dest: /tmp/nodecerts/
    remote_src: yes
  run_once: true
  tags: tlstool

- name: Make the executable file
  local_action:
    module: file
    dest: /tmp/nodecerts/tools/sgtlstool.sh
    mode: a+x
  run_once: true
  tags: tlstool

- name: Prepare the certificates generation template file
  local_action:
    module: template
    src: tlsconfig.yml.j2
    dest: /tmp/nodecerts/config/tlsconfig.yml
  tags: tlstool
 
- name: Generate the node & admin certificates in local
  local_action:
    module: command /tmp/nodecerts/tools/sgtlstool.sh -c /tmp/nodecerts/config/tlsconfig.yml -ca -crt -t /tmp/nodecerts/config/
  run_once: true
  tags: get_certs

- name: Copy node, root and admin certificates
  copy:
    src: "/tmp/nodecerts/config/{{ item }}"
    dest: "{{ opensearch_data_dir }}/certs"
    owner: '1000'
    mode: 0600
  with_items:
    - "node-{{ ansible_hostname }}.key"
    - "node-{{ ansible_hostname }}.pem"
    - "node-{{ ansible_hostname }}_http.key"
    - "node-{{ ansible_hostname }}_http.pem"
    - "{{ ansible_hostname }}-kibana_http.pem"
    - "{{ ansible_hostname }}-kibana_http.key"
    - admin.key
    - admin.pem
    - root-ca.pem
    - root-ca.key
  tags: copy_certs

- name: Remove local temporary directory for certificates generation
  local_action:
    module: file
    path: /tmp/nodecerts
    state: absent
  run_once: true
  tags: tmp_folder_rm
