---
# - name: containerd | Generate systemd service for containerd
#   template:
#     src: containerd.service.j2
#     dest: /etc/systemd/system/containerd.service
#     mode: 0644
#   notify: restart containerd

# - name: containerd | Ensure containerd directories exist
#   file:
#     dest: "{{ item }}"
#     state: directory
#     mode: 0755
#     owner: root
#     group: root
#   with_items:
#     - "{{ containerd_systemd_dir }}"
#     - "{{ containerd_cfg_dir }}"
#     - "{{ containerd_storage_dir }}"
#     - "{{ containerd_state_dir }}"
#   tags: check_dir

- name: containerd | Copy containerd config file
  template:
    src: config.toml.j2
    dest: "{{ containerd_cfg_dir }}/config.toml"
    backup: yes
    owner: "root"
    mode: 0640
  notify: restart containerd
  tags: deploy_config

- name: containerd | Ensure containerd is started and enabled
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    state: started
  tags: systemd