- name: Получаем список существующих пользователей
  ansible.builtin.shell: radosgw-admin user list | jq -r '.[]'
  register: existing_users
  changed_when: false

- name: Сохраняем список существующих пользователей
  ansible.builtin.set_fact:
    existing_users_list: "{{ existing_users.stdout_lines }}"

# --- Создание пользователей ---
- name: Проверяем пользователей в проекте {{ project.key }}
  ansible.builtin.shell: |
    radosgw-admin user info --uid={{ item.value.name }} 2>/dev/null || echo "USER_NOT_FOUND"
  register: user_info
  changed_when: false
  with_dict: "{{ project.value.users }}"

- name: "Создаём пользователей в {{ project.key }}"
  ansible.builtin.shell: |
    radosgw-admin user create --uid={{ item.value.name }} \
      --display-name="{{ item.value.name }}" \
      --placement-id={{ project.value.placement }} \
      --caps="{{ item.value.caps }}"
  when: "'USER_NOT_FOUND' in item.1.stdout"
  with_dict: "{{ project.value.users }}"
  register: user_creation

- name: "Обновляем caps у существующих пользователей в {{ project.key }}"
  ansible.builtin.shell: |
    radosgw-admin user modify --uid={{ item.value.name }} --caps="{{ item.value.caps }}"
  when: "'USER_NOT_FOUND' not in item.1.stdout"
  with_dict: "{{ project.value.users }}"
  register: user_caps_update
  changed_when: "'caps' in user_caps_update.stdout"

# --- Создание бакетов ---
- name: "Создание бакетов в {{ project.key }}"
  ansible.builtin.shell: |
    AWS_ACCESS_KEY_ID={{ project.value.admin.access_key }} \
    AWS_SECRET_ACCESS_KEY={{ project.value.admin.secret_key }} \
    aws --endpoint-url {{ ceph_endpoint }} s3api create-bucket --bucket {{ item.value.name }}
  with_dict: "{{ project.value.buckets }}"
  register: bucket_creation
  changed_when: "'Bucket' in bucket_creation.stdout"

# --- Обновление политик пользователей ---
- name: "Получаем текущие политики пользователей в {{ project.key }}"
  ansible.builtin.shell: |
    AWS_ACCESS_KEY_ID={{ project.value.admin.access_key }} \
    AWS_SECRET_ACCESS_KEY={{ project.value.admin.secret_key }} \
    aws --endpoint-url {{ ceph_endpoint }} iam list-user-policies --user-name {{ item.value.name }} | jq -r '.PolicyNames[]'
  register: current_policies
  with_dict: "{{ project.value.users }}"
  changed_when: false

- name: "Удаляем ненужные политики в {{ project.key }}"
  ansible.builtin.shell: |
    AWS_ACCESS_KEY_ID={{ project.value.admin.access_key }} \
    AWS_SECRET_ACCESS_KEY={{ project.value.admin.secret_key }} \
    aws --endpoint-url {{ ceph_endpoint }} iam delete-user-policy \
      --user-name {{ item.0.value.name }} --policy-name {{ item.1 }}
  when: item.1 not in item.0.value.policies.keys()
  with_subelements:
    - "{{ project.value.users }}"
    - current_policies.stdout_lines

- name: "Назначаем политики пользователям в {{ project.key }}"
  ansible.builtin.shell: |
    cat > /tmp/policy_{{ item.0.value.name }}.json <<EOF
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "{{ item.1.value.sid }}",
          "Effect": "{{ item.1.value.effect | capitalize }}",
          "Action": {{ item.1.value.action | to_json }},
          "Resource": {{ item.1.value.resource | to_json }}
        }
      ]
    }
    EOF
    AWS_ACCESS_KEY_ID={{ project.value.admin.access_key }} \
    AWS_SECRET_ACCESS_KEY={{ project.value.admin.secret_key }} \
    aws --endpoint-url {{ ceph_endpoint }} iam put-user-policy \
      --user-name {{ item.0.value.name }} \
      --policy-name {{ item.1.value.name }} \
      --policy-document file:///tmp/policy_{{ item.0.value.name }}.json
  with_subelements:
    - "{{ project.value.users }}"
    - policies
  register: policy_assignment
  changed_when: "'Policy' in policy_assignment.stdout"

# --- Отключение пользователей, которых нет в Project ---
- name: "Приостанавливаем пользователей, не указанных в {{ project.key }}"
  ansible.builtin.shell: |
    radosgw-admin user suspend --uid={{ item }}
  when: item not in project.value.users.keys()
  with_items: "{{ existing_users_list }}"
