---
# переменные inventory host_vars/ выше inventory group_vars/all, inventory group_vars/ и переменных в inventory file
docker_path_data: /opt/data/opensearch-cluster-data
docker_path: /data/docker

# Objects for logging
bash_log: false # logging bash users commands
#bash_path_to_logs: /var/log/bash/bash.log # path to log file on host

# Filebeat: path to log files on host
#path_to_logs:
#    - dc: '/data/logs:/data/logs' # docker-compose volumes mapping
#    - dc: '/logs:/logs' # docker-compose volumes mapping

################## vars for deploy docker-compose file
ls_java_opt: # minimum and maximum Java heap size (use Mb)
     min: '512m'
     max: '512m'

################## snapshot
#путь до репозитория, если единый, то указать в group_vars/opensearch/opensearch.yml
opensearch_snapshot_path: /opt/nfs-client-odfe2
#расписание cron, если единое, то указать в group_vars/opensearch/opensearch.yml
#opensearch_snapshot_script_cron: '2,8,14,20'
