---
# переменные inventory host_vars/ выше inventory group_vars/all, inventory group_vars/ и переменных в inventory file
docker_path_data: /data/opensearch-cluster-data
docker_path: /data/docker

# Objects for logging
bash_log: false # logging bash users commands
#bash_path_to_logs: /var/log/bash/bash.log # path to log file on host

# Filebeat: path to log files on host
#path_to_logs:
#    - dc: '/data/logs:/data/logs' # docker-compose volumes mapping
#    - dc: '/logs:/logs' # docker-compose volumes mapping

################## vars for deploy docker-compose file
ls_java_opt: # minimum and maximum Java heap size (use Mb)
     min: '512m'
     max: '512m'

################## snapshot
#путь до репозитория, если единый, то указать в group_vars/opensearch/opensearch.yml
opensearch_snapshot_path: /opt/nfs-client-odfe3
#расписание cron, если единое, то указать в group_vars/opensearch/opensearch.yml
#opensearch_snapshot_script_cron: '4,10,16,22'

################## indices and actions for delete indices older than X seconds, minutes, hours, days, weeks, months, or years (based on index name).
# расписание cron, если разное, то указать для каждого хоста в host_vars, если единое, то тут.
curator_delete_indices_script_cron:
    minute: '30'
    hour: '1'
# отправлять сообщение об ошибке при выполнение action
telegram:
    send_msg: true
    bot_token: 1727026763:AAHd4x9AzzUWTJ_r_xvQiFzD8Xx_MwD6q-A
    chat_id: '-1001811774275'
# отправлять сообщение об удаленных индексах и снапшотах
email:
    send_msg: True
    smtp_url: 'smtp://ctpmail:Wzx567Inm@10.80.7.7:25'
    send_to: "kalininov@intech.rshb.ru, tarasovdl@intech.rshb.ru"
# удалять индексы старше n-дней или n-месяцев
curator_delete_indices:
# Примеры:
#    - action: delete_other_indices # action script name
#      kind: regex # prefix (logstash-), suffix (-prod), timestring (%Y.%m.%d) or regex (^a-|^b-|^c-) (default: prefix)
#      value: other-
#      direction: older # older or younger (default: older)
#      timestring: '%Y.%m' # if unit=months '%Y.%m', if unit=days '%Y.%m.%d' or set manually
#      unit: months # seconds, minutes, hours, days, weeks, months, or years
#      unit_count: 1
#      exclude: False # True (the filter will remove matches from the actionable list) or False (only matches will be kept in the actionable list) (default: False)
#    - action: delete_other-and-odfe_indices
#      kind: regex
#      value: ^(other|odfe-filebeat|odfe-kibana|odfe-elasticsearch|dtln-prod-odfe-logstash|odfe-logstash)-*
#      unit: months
#      unit_count: 1
    - action: delete_other_indices
      value: other-
      unit: months
      unit_count: 2
    - action: delete_odfe_indices
      kind: regex
      value: ^(odfe|dtln-dev-odfe-logstash)-*
      unit: months
      unit_count: 2
    - action: delete_aav-elasticsearch-nginx_indices
      kind: regex
      value: ^(aav-elasticsearch|aav-nginx)-*
      unit: months
      unit_count: 2
    - action: delete_digital-wcms-nginx-dev_indices
      value: digital-wcms-nginx-dev-dtln-
      unit: months
      unit_count: 2
    - action: delete_digital-wcms-nginx-preprod_indices
      value: digital-wcms-nginx-preprod-dtln-
      unit: months
      unit_count: 2
    - action: delete_security-auditlog-days_indices
      kind: regex
      value: 'security-auditlog-\d{4}\.\d{2}\.\d{2}$'
      unit: days
      unit_count: 14
    - action: delete_sb-ol-dex_indices
      value: sb-ol-dex-
      unit: months
      unit_count: 2
    - action: delete_dev-dex_indices
      value: dev-dex-
      unit: months
      unit_count: 2
# gentics-mesh
    - action: delete_gentics-mesh-elasticsearch_indices
      value: gentics-mesh-elasticsearch-
      unit: months
      unit_count: 2
    - action: delete_gentics-mesh-proxy_indices
      value: gentics-mesh-proxy-
      unit: months
      unit_count: 2
    - action: delete_gentics-mesh-ui_indices
      value: gentics-mesh-ui-
      unit: months
      unit_count: 2
# mps
    - action: delete_mps-days_indices
      kind: regex
      value: '^mps.*$'
      unit: days
      unit_count: 3
# cos
    - action: delete_cos-ad-importer_indices
      value: cos-ad-importer-
      unit: months
      unit_count: 2
    - action: delete_cos-administration_indices
      value: cos-administration-
      unit: months
      unit_count: 2
    - action: delete_cos-calendar_indices
      kind: regex
      value: '^cos-calendar-\d{4}\.\d{2}$'
      unit: months
      unit_count: 2
    - action: delete_cos-calendar-aggregator_indices
      value: cos-calendar-aggregator-
      unit: months
      unit_count: 2
    - action: delete_cos-center-notification_indices
      value: cos-center-notification-
      unit: months
      unit_count: 2
    - action: delete_cos-cms_indices
      value: cos-cms-
      unit: months
      unit_count: 2
    - action: delete_cos-corp-importer_indices
      value: cos-corp-importer-
      unit: months
      unit_count: 2
    - action: delete_cos-corp-photo-importer_indices
      value: cos-corp-photo-importer-
      unit: months
      unit_count: 2
    - action: delete_cos-credential-service_indices
      value: cos-credential-service-
      unit: months
      unit_count: 2
    - action: delete_cos-demo-app_indices
      value: cos-demo-app-
      unit: months
      unit_count: 2
    - action: delete_cos-discovery-server_indices
      value: cos-discovery-server-
      unit: months
      unit_count: 2
    - action: delete_cos-dtln-test-gm-assist-db_indices
      value: cos-dtln-test-gm-assist-db-
      unit: months
      unit_count: 2
    - action: delete_cos-dtln-test-gm-assist_indices
      value: cos-dtln-test-gm-assist-
      unit: months
      unit_count: 2
    - action: delete_cos-dtln-test-gm-elasticsearch_indices
      value: cos-dtln-test-gm-elasticsearch-
      unit: months
      unit_count: 2
    - action: delete_cos-dtln-test-gm-server_indices
      value: cos-dtln-test-gm-server-
      unit: months
      unit_count: 2
    - action: delete_cos-dtln-test-gm-ui_indices
      value: cos-dtln-test-gm-ui-
      unit: months
      unit_count: 2
    - action: delete_cos-dtln-test-gm-proxy_indices
      value: cos-dtln-test-gm-proxy-
      unit: months
      unit_count: 2
    - action: delete_cos-feign-client_indices
      value: cos-feign-client-
      unit: months
      unit_count: 2
    - action: delete_cos-file-service_indices
      value: cos-file-service-
      unit: months
      unit_count: 2
    - action: delete_cos-gateway-server_indices
      value: cos-gateway-server-
      unit: months
      unit_count: 2
    - action: delete_cos-itms-connector_indices
      value: cos-itms-connector-
      unit: months
      unit_count: 2
    - action: delete_cos-lotus-calendar_indices
      value: cos-lotus-calendar-
      unit: months
      unit_count: 2
    - action: delete_cos-notice-service_indices
      value: cos-notice-service-
      unit: months
      unit_count: 2
    - action: delete_cos-notifier-service_indices
      value: cos-notifier-service-
      unit: months
      unit_count: 2
    - action: delete_cos-org-structure_indices
      value: cos-org-structure-
      unit: months
      unit_count: 2
    - action: delete_cos-paramservice_indices
      value: cos-paramservice-
      unit: months
      unit_count: 2
    - action: delete_cos-platform-api_indices
      value: cos-platform-api-
      unit: months
      unit_count: 2
    - action: delete_cos-portal-config_indices
      value: cos-portal-config-
      unit: months
      unit_count: 2
    - action: delete_cos-sap-importer_indices
      value: cos-sap-importer-
      unit: months
      unit_count: 2
    - action: delete_cos-services-app_indices
      value: cos-services-app-
      unit: months
      unit_count: 2
    - action: delete_cos-statisticreport_indices
      value: cos-statisticreport-
      unit: months
      unit_count: 2
    - action: delete_cos-statistic-service_indices
      value: cos-statistic-service-
      unit: months
      unit_count: 2
    - action: delete_cos-survey-test_indices
      value: cos-survey-test-
      unit: months
      unit_count: 2
    - action: delete_cos-us-app_indices
      value: cos-us-app-
      unit: months
      unit_count: 2
    - action: delete_cos-x-matrix_indices
      value: cos-x-matrix-
      unit: months
      unit_count: 2
# job-edu and vsesvoe (ЯвАгро ВсеСвое)
    - action: delete_dev-job-dev-back_indices
      value: job-dev-back-
      unit: months
      unit_count: 2
    - action: delete_job-test-back_indices
      value: job-test-back-
      unit: months
      unit_count: 2
    - action: delete_dev-job-edu-back_indices
      value: dev-job-edu-back-
      unit: months
      unit_count: 2
    - action: delete_job-edu_indices
      kind: regex
      value: '^job-edu-\d{4}\.\d{2}$'
      unit: months
      unit_count: 2
    - action: delete_job-edu-laravel_indices
      value: job-edu-laravel-
      unit: months
      unit_count: 2
    - action: delete_vsesvoe_indices
      value: vsesvoe-
      unit: months
      unit_count: 2
    - action: delete_vse-svoe_indices
      value: vse-svoe-
      unit: months
      unit_count: 2
# varshb (чат-бот)
    - action: delete_vmrshb_communication_center_indices
      value: vmrshb_communication_center-
      unit: months
      unit_count: 3
    - action: delete_varshb_communication_center_indices
      value: varshb_communication_center-
      unit: months
      unit_count: 3
    - action: delete_varshb_currency_sync_indices
      value: varshb_currency_sync-
      unit: months
      unit_count: 3
    - action: delete_varshb_distribution_center_indices
      value: varshb_distribution_center-
      unit: months
      unit_count: 3
    - action: delete_varshb_sampler_indices
      value: varshb_sampler-
      unit: months
      unit_count: 3
    - action: delete_varshb_svoe_rodnoe_indices
      value: varshb_svoe_rodnoe-
      unit: months
      unit_count: 3
    - action: delete_varshb_telegram_bot_indices
      value: varshb_telegram_bot-
      unit: months
      unit_count: 3
# crshb
    - action: delete_crshb_indices
      value: crshb-
      unit: months
      unit_count: 2
# agrolider
    - action: delete_agrolider_indices
      value: agrolider-
      unit: months
      unit_count: 2
# b2b (fermerstvo)
    - action: delete_b2b_indices
      value: b2b-
      unit: months
      unit_count: 2
# b2c (svoe rodnoe)
    - action: delete_b2c_indices
      value: b2c-
      unit: months
      unit_count: 3
# coins
    - action: delete_coins_indices
      value: coins-
      unit: months
      unit_count: 2
# agrotour
    - action: delete_agro_indices
      value: agro-
      unit: months
      unit_count: 2
    - action: delete_agrotour_indices
      value: agrotour-
      unit: months
      unit_count: 2
# powerdns
    - action: delete_powerdns_indices
      value: powerdns-
      unit: months
      unit_count: 2
# pszh
    - action: delete_pszh_indices
      value: pszh-
      unit: months
      unit_count: 2