{
 "title": "Docker monitoring Full",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "docker",
  "mini"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(container_tasks_state{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_tasks_state, job)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Disk $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk IOs Current in Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops", "label": "I/Os" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_io_current{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOs Weighted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_io_time_weighted_seconds_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}"
    }
   ]
  },
  {
   "title": "Disk R/W Merged",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "iops", "label": "I/Os" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_merged_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}-R"
    },
    {
     "expr": "irate(container_fs_writes_merged_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}-W"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "R (-) / W (+)" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}-R"
    },
    {
     "expr": "irate(container_fs_writes_bytes_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}-W"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Millisec. r (-) / w (+)" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_read_seconds_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}-R"
    },
    {
     "expr": "irate(container_fs_write_seconds_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}-W"
    }
   ]
  },
  {
   "title": "Milliseconds Spent Doing I/Os",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_io_time_seconds_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "graph",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "iops", "label": "IO r (-) / w (+)" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}-R"
    },
    {
     "expr": "irate(container_fs_writes_total{image!=\"\",job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{host}}:{{name}},{{device}}-W"
    }
   ]
  },
  { "title": "CPU/Mem $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 30 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",instance=~\"$instance\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",instance=~\"$instance\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\",instance=~\"$instance\"}[5m]) * 100",
     "legendFormat": "{{name}} ({{host}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} ({{host}})"
    }
   ]
  }
 ]
}