{
 "title": "Docker monitoring Mini",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "docker",
  "mini"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_tasks_state, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(container_tasks_state{job=~\"$job\"}, instance)"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(container_tasks_state{instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",instance=~\"$instance\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",instance=~\"$instance\",name=~\"$name\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m]) * 100",
     "legendFormat": "{{name}} ({{host}})-user"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m]) * 100",
     "legendFormat": "{{name}} ({{host}})-system"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}} ({{host}})-usage"
    },
    {
     "expr": "container_memory_cache{image!=\"\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}} ({{host}})-cache"
    },
    {
     "expr": "container_memory_rss{image!=\"\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}} ({{host}})-rss"
    },
    {
     "expr": "container_memory_working_set_bytes{image!=\"\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}} ({{host}})-working"
    },
    {
     "expr": "container_memory_swap{image!=\"\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}} ({{host}})-swap"
    }
   ]
  },
  {
   "title": "Memory Failure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "irate(container_memory_failures_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m])",
     "legendFormat": "{{name}} ({{host}}){{failure_type}}-{{scope}}"
    }
   ]
  },
  {
   "title": "Rx/Tx Packet Dropped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_dropped_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[1m])",
     "legendFormat": "Rx-{{name}}-{{interface}}"
    },
    {
     "expr": "irate(container_network_transmit_packets_dropped_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[1m])",
     "legendFormat": "Tx-{{name}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Network Rx/Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m])",
     "legendFormat": "RX-{{name}} ({{host}}){{interface}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m])",
     "legendFormat": "TX-{{name}} ({{host}}){{interface}}"
    }
   ]
  },
  {
   "title": "Network Rx/Tx - Packet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m])",
     "legendFormat": "Rx-{{name}} - {{interface}}"
    },
    {
     "expr": "rate(container_network_transmit_packets_total{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m])",
     "legendFormat": "Tx-{{name}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Disk IOs Current in Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "iops", "label": "I/Os" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_io_current{image!=\"\",instance=~\"$instance\",name=~\"$name\"}[5m])",
     "legendFormat": "{{name}}-{{device}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps", "label": "R (-) / W (+)" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{image!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[5m])",
     "legendFormat": "{{name}}-{{device}}-R"
    },
    {
     "expr": "irate(container_fs_writes_bytes_total{image!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[5m])",
     "legendFormat": "{{name}}-{{device}}-W"
    }
   ]
  }
 ]
}