{
 "title": "Elasticsearch Mini",
 "description": "Grafana Dashboards for Elasticsearch using Prometheus Datasource",
 "tags": [
  "elasticsearch",
  "es-cluster",
  "mini"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": {
     "query": "label_values(elasticsearch_node_stats_up, instance)"
    }
   },
   {
    "name": "name",
    "label": "Node name",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},name)"
    }
   },
   {
    "name": "interval",
    "label": "Rate Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{cluster=\"$cluster\",instance=\"$instance\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",instance=\"$instance\",color=\"yellow\"}==1)+2 or\n(elasticsearch_cluster_health_status{cluster=\"$cluster\",instance=\"$instance\",color=\"green\"}==1)+4 "
    }
   ]
  },
  {
   "title": "CPU  Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (elasticsearch_process_cpu_percent{cluster=\"$cluster\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Indices",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (elasticsearch_indices_docs_primary{cluster=\"$cluster\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "singlestat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "singlestat",
   "description": "On primary shards",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs_primary{cluster=\"$cluster\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Segments",
   "type": "singlestat",
   "description": "On all nodes\n\n*A segment is a file, aka a lucene index*",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (elasticsearch_indices_segment_count_total{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",instance=\"$instance\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Max Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_pool_max_bytes{cluster=\"$cluster\",instance=\"$instance\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "singlestat",
   "description": "% Memory used by selected nodes, both heap and non-heap",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",instance=\"$instance\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",instance=\"$instance\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "App Indices",
   "type": "singlestat",
   "description": "Number of indices not starting with a dot (.)",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (elasticsearch_indices_docs_primary{cluster=\"$cluster\",instance=\"$instance\",index!~\"\\\\..*\"})"
    }
   ]
  },
  {
   "title": "Data",
   "type": "singlestat",
   "description": "On all shards",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes_total{cluster=\"$cluster\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Primary Segments",
   "type": "singlestat",
   "description": "On primary shards\n\n*A segment is a file, aka a lucene index*",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (elasticsearch_indices_segment_count_primary{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Shards",
   "type": "singlestat",
   "description": "All shards, both primary and replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Primary Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "singlestat",
   "description": "Number of shards which are relocating to another node",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Delayed Shards",
   "type": "singlestat",
   "description": "Number of shards which are delayed relocating to another node",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\",instance=\"$instance\"} "
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "singlestat",
   "description": "Number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\",instance=\"$instance\"} "
    }
   ]
  },
  {
   "type": "table-old",
   "description": "Current status of all nodes in cluster\n\n###### Notes\n\n+ `Blue`: constant value\n+ `Fds`: File Descriptors\n+ `Throttle`: flag `is_throttled`\n",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (name) (elasticsearch_os_cpu_percent{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (name) (elasticsearch_os_load5{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Load Average"
    },
    {
     "expr": "sum by (name) (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",instance=~\"$instance\"}) / sum by (name) (elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",instance=~\"$instance\"}) * 100",
     "legendFormat": "JVM Memory"
    },
    {
     "expr": "sum by (name) (elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Disk Free Space"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{cluster=\"$cluster\",instance=~\"$instance\",role=\"master\"})",
     "legendFormat": "Master Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{cluster=\"$cluster\",instance=~\"$instance\",role=\"data\"})",
     "legendFormat": "Data Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{cluster=\"$cluster\",instance=~\"$instance\",role=\"ingest\"})",
     "legendFormat": "Ingest Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{cluster=\"$cluster\",instance=~\"$instance\",role=\"client\"})",
     "legendFormat": "Client Node"
    },
    {
     "expr": "1 - sum by (name) (elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",instance=~\"$instance\"}) / sum by (name) (elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "% Disk Used"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_store_size_bytes{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Index Store Data"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_segments_memory_bytes{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Segment Memory"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_segments_count{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Segment Count"
    },
    {
     "expr": "sum by (name) (elasticsearch_process_open_files_count{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Open Fds"
    },
    {
     "expr": "sum by (name) (elasticsearch_process_max_files_descriptors{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Max Fds"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_indexing_is_throttled{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Throttle"
    }
   ]
  },
  {
   "title": "Cluster Indexing",
   "type": "stat",
   "description": "Indexing rate on cluster\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for these requests.\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\nsum (rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",instance=~\"$instance\"}[$interval])) / \nsum (rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",instance=~\"$instance\"}[$interval]))\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Cluster Search",
   "type": "stat",
   "description": "Searching rate on cluster\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for those requests.\n",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\n(sum(rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",instance=~\"$instance\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\",instance=~\"$instance\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_scroll_time_seconds{cluster=\"$cluster\",instance=~\"$instance\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_suggest_time_seconds{cluster=\"$cluster\",instance=~\"$instance\"}[$interval]))\n) /\nsum(rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\",instance=~\"$instance\"}[$interval]))\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Indexing ReqRate (req/s)",
   "type": "stat",
   "description": "Indexing rate on data nodes",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",instance=\"$instance\",name=~\"$name\",es_data_node=\"true\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search Query ReqRate (req/s)",
   "type": "stat",
   "description": "Search query rate on data nodes",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\",instance=\"$instance\",name=~\"$name\",es_data_node=\"true\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}