{
 "title": "JVM & Tomcat",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with Tomcat metrics",
 "tags": [
  "JVM",
  "tomcat"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "java" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", instance=\"$instance\"}, pool)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{job=\"$job\", instance=\"$instance\"}, area)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "label_values(tomcat_bytesreceived_total{job=\"$job\", instance=~\"$instance\"}, protocol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server info",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_serverinfo{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_maxthreads{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Min spare threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_minsparethreads{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Acceptor thread count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptorthreadcount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Poller thread count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_pollerthreadcount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Accept count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptcount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 8 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\",instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_open_file_descriptor_count{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_available_processors{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_system_load_average{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{job=\"$job\",instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Session count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tomcat_session_sessioncounter_total{job=\"$job\", instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "New"
    },
    {
     "expr": "sum(increase(tomcat_session_expiredsessions_total{job=\"$job\", instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(increase(tomcat_session_rejectedsessions_total{job=\"$job\", instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Session current count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{job=\"$job\", instance=\"$instance\"} - tomcat_session_expiredsessions_total)"
    }
   ]
  },
  {
   "title": "Session total created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Session total expired",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_expiredsessions_total{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top 5 servlet request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_requestcount_total{job=\"$job\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "module={{module}} servlet={{servlet}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet error count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_errorcount_total{job=\"$job\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "module={{module}} servlet={{servlet}}"
    }
   ]
  },
  {
   "title": "Traffic send/recv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_bytesreceived_total{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Received {{protocol}}[{{port}}]"
    },
    {
     "expr": "increase(tomcat_bytessent_total{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Sent {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "Request  count / error count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_requestcount_total{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Request {{protocol}}[{{port}}]"
    },
    {
     "expr": "increase(tomcat_errorcount_total{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Error {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "Top 5 servlets average processing time per request",
   "type": "graph",
   "description": "Top 4 servlets average processing time per request in last 5 minutes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_processingtime_total{job=\"$job\", instance=\"$instance\"}[$__interval]) / increase(tomcat_servlet_requestcount_total{job=\"$job\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "module {{module}} servlet {{servlet}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadcount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}",
     "legendFormat": "current {{protocol}}[{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}",
     "legendFormat": "current busy  {{protocol}}[{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_connectioncount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}",
     "legendFormat": "connection  {{protocol}}[{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_keepalivecount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}",
     "legendFormat": "keep alive  {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "os_system_cpu_load{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "System"
    },
    {
     "expr": "os_process_cpu_load{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\",instance=\"$instance\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_total_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "os_committed_virtual_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed virtual memory"
    },
    {
     "expr": "os_free_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Free physical memory"
    }
   ]
  }
 ]
}