{
 "title": "Keepalived Status",
 "tags": [
  "keepalived",
  "ha",
  "mini"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "node_name",
    "query": {
     "query": "label_values(keepalived_up,node_name)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "state",
    "label": "state",
    "query": {
     "query": "label_values(keepalived_vrrp_state, state)"
    }
   },
   { "name": "vrrp_script", "label": "vrrp_script", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "VRRP status",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 10, "x": 2, "y": 0 },
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "Service status",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 10, "x": 12, "y": 0 },
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "Service uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_uptime{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_up{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Script Status: $vrrp_script",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_script_status{node_name=~\"$node_name\"}",
     "legendFormat": "{{vrrp_script}}"
    }
   ]
  },
  {
   "title": "VRRP State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{node_name=~\"$node_name\"}",
     "legendFormat": "{{ state }} "
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "keepalived_up{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "VRRP State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "keepalived_vrrp_state{node_name=~\"$node_name\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}