{
 "title": "Keycloak Metrics",
 "description": "Monitoring keycloak metrics",
 "tags": [ "keycloack" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(keycloak_logins,instance)"
    }
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": {
     "query": "label_values(keycloak_logins{instance=\"$instance\",job=\"keycloak\",provider=\"keycloak\"},realm)"
    }
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": {
     "query": "label_values(keycloak_logins{instance=\"$instance\",job=\"keycloak\",provider=\"keycloak\",realm=\"$realm\"},client_id)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Memory HEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"heap\"})\n"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_init{instance=\"$instance\"})",
     "legendFormat": "init"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_init{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "init"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_init{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "init"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=\"$instance\"}",
     "legendFormat": "deadlocked"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{gc}} "
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_memory_pool_allocated_bytes_tota{instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\"}[1m])/rate(jvm_gc_collection_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "avg  ({{gc}})"
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded{instance=\"$instance\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{instance=\"$instance\", pool=\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_pool_capacity_bytes{instance=\"$instance\", pool=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_buffers{instance=\"$instance\", pool=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{instance=\"$instance\",pool=\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_pool_capacity_bytes{instance=\"$instance\",pool=\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_buffers{instance=\"$instance\", pool=\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "KK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Logins Per REALM",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_logins{instance=\"$instance\"}) by (realm)",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 44 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_logins{instance=\"$instance\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registrations Per CLIENT",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_registrations{instance=\"$instance\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Logins per REALM per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_logins{instance=\"$instance\",job=\"keycloak\"}[1m]))",
     "legendFormat": "{{realm}}"
    },
    {}
   ]
  },
  {
   "title": "Login Errors on realm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts{instance=\"$instance\",job=\"keycloak\",provider=\"keycloak\",realm=\"$realm\"}[1m])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_logins{instance=\"$instance\",job=\"keycloak\",realm=\"$realm\",provider=\"keycloak\"}[60s])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Login Errors for $ClientId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts{instance=\"$instance\",job=\"keycloak\",provider=\"keycloak\",realm=\"$realm\",client_id=\"$ClientId\"}[1m])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Registrations per CLIENT on relm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_registrations{instance=\"$instance\",job=\"keycloak\",realm=\"$realm\",provider=\"keycloak\"}[1h])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registration Errors for $ClientId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_registrations_errors{instance=\"$instance\",job=\"keycloak\",provider=\"keycloak\",realm=\"$realm\",client_id=\"$ClientId\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}