{
 "title": "Logstash metrics",
 "description": "Logstash monitoring via prometheus",
 "tags": [
  "prometheus",
  "elasticsearch",
  "logstash"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,30s,1m,5m,1h,6h,1d" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(logstash_info_node,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dead letter queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dead letter queue size bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "logstash_node_dead_letter_queue_size_bytes{instance=~\"$instance\"}[$interval]",
     "legendFormat": "{{pipeline}}{{instance}}"
    }
   ]
  },
  {
   "title": "Dead letter queue size bytes counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(logstash_node_dead_letter_queue_size_bytes{instance=~\"$instance\"}[$interval])) by (pipeline)",
     "legendFormat": "{{pipeline}}{{instance}}"
    }
   ]
  },
  { "title": "PIPELINE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Duration rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_duration_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Events in rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_in_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Events filtered rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_filtered_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Events out rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_out_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  { "title": "PLUGINS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Duration rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_duration_seconds_total{instance=~\"$instance\"}[$interval])) by (plugin,pipeline)",
     "legendFormat": "{{pipeline}}-{{plugin}}"
    }
   ]
  },
  {
   "title": "Failures rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(logstash_node_plugin_failures_total{instance=~\"$instance\"}[$interval])) by (plugin,pipeline)",
     "legendFormat": "{{pipeline}}-{{plugin}}"
    }
   ]
  },
  {
   "title": "Events In rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_in_total{instance=~\"$instance\"}[$interval])) by (plugin,pipeline)",
     "legendFormat": "{{pipeline}}-{{plugin}}"
    }
   ]
  },
  {
   "title": "Events Out rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_out_total{instance=~\"$instance\"}[$interval])) by (plugin,pipeline)",
     "legendFormat": "{{pipeline}}-{{plugin}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_mem_heap_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - heap used"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_process_open_filedescriptors{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "increase(logstash_node_gc_collection_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_duration_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  }
 ]
}