{
 "title": "PostgreSQL: pgSCV",
 "description": "PostgreSQL dashboard for pgSCV metrics (Prometheus version, pgSCV 0.7.0 edition)",
 "time": { "from": "now-15m", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(pgscv_services_registered_total, instance)"
   },
   {
    "name": "postgres",
    "label": "service_id",
    "query": "label_values(pgscv_services_registered_total{instance=~\"$instance\"}, service_id)"
   },
   {
    "name": "database",
    "query": "label_values(postgres_statements_calls_total{service_id=~\"$postgres\"}, database)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Current status of PostgreSQL service.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_up{instance=\"$instance\",service_id=\"$postgres\"}",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Statements",
   "type": "stat",
   "description": "Rate of successfully executed statements per second.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "statements"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of log messages rate (per minute) with severity higher than LOG (e.g. WARNING, ERROR, FATAL and PANIC).",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postgres_log_messages_total{level!=\"log\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Response Time, avg",
   "type": "stat",
   "description": "Average response time calculated using time of executed statements.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_statements_time_seconds_all_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) / sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Longest Activity",
   "type": "stat",
   "description": "Current longest transaction activity, initiated by clients or background service (e.g. autovacuum).",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "description": "Total number of connected clients.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Activity",
     "type": "graph",
     "description": "Query activity produced by connected clients.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "statements"
      },
      {
       "expr": "sum(rate(postgres_database_xact_commits_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "commits"
      },
      {
       "expr": "sum(rate(postgres_database_xact_rollbacks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "rollbacks"
      }
     ]
    },
    {
     "title": "Longest Activity",
     "type": "graph",
     "description": "The most longest activity produced by connected clients and background services.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, max by (user) (postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "Client Connections",
     "type": "graph",
     "description": "States of connections established by clients (doesn't include states of background services).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log messages, per minute",
     "type": "graph",
     "description": "Messages written to log, by severity.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (level) (increase(postgres_log_messages_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "Log directory, bytes",
     "type": "graph",
     "description": "Total size of log directory in bytes.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgres_log_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ path }}"
      }
     ]
    },
    {
     "title": "Logging settings",
     "type": "table",
     "description": "Important: when logging_collector is disabled, log metrics will not be collected.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"logging_collector|log_directory|log_filename\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements (pg_stat_statements required)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Calls",
     "type": "graph",
     "description": "The top-most executed statements.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_calls_total{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "graph",
     "description": "The top-most statements by returned rows.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_rows_total{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Total time",
     "type": "graph",
     "description": "The top-most statements by total time (planning, executing and doing IO).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_time_seconds_all_total{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "IO time",
     "type": "graph",
     "description": "The top-most statements by IO time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum without (mode) (rate(postgres_statements_time_seconds_total{mode=~\"ioread|iowrite\",instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks and Wait Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Events, by type",
     "type": "graph",
     "description": "Wait events aggregated by type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (postgres_activity_wait_events_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Wait Events",
     "type": "graph",
     "description": "The top-most wait events occurred.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_activity_wait_events_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ type }}:{{ event }}"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "graph",
     "description": "Total number of locks acquired.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_locks_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Deadlocks, per minute",
     "type": "graph",
     "description": "Total number of deadlocks per minute.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(postgres_database_deadlocks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "deadlocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag, bytes",
     "type": "graph",
     "description": "Total amount of replication lag, when standbys left behind the master.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (client_addr) (postgres_replication_lag_all_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ client_addr }}"
      }
     ]
    },
    {
     "title": "Replication Lag, seconds",
     "type": "graph",
     "description": "Total amount of replication lag, when standbys left behind the master.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (client_addr) (postgres_replication_lag_all_seconds{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ client_addr }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL write, bytes per second",
     "type": "graph",
     "description": "Amount of WAL generated or received by Postgres instance.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(postgres_wal_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "WAL"
      }
     ]
    },
    {
     "title": "WAL directory size",
     "type": "graph",
     "description": "Total size of WAL directory, in bytes.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgres_wal_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "WAL settings",
     "type": "table",
     "description": "WAL settings",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"(max|min)_wal_size|max_slot_wal_keep_size|full_page_writes|wal_keep_(size|segments)|wal_(compression|level|log_hints)\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Vacuum Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vacuums",
     "type": "graph",
     "description": "Total number of automatic and user-initiated vacuum operations.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_activity_vacuums_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Vacuumed tables, per-minute",
     "type": "graph",
     "description": "The top-most vacuumed tables.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(postgres_table_maintenance_total{type=\"autovacuum\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Autovacuum settings",
     "type": "table",
     "description": "Autovacuum settings.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"^(auto)?vacuum.+\"})"
      }
     ]
    },
    {
     "title": "Transactions left before wraparound",
     "type": "graph",
     "description": "Total number transactions left before XID wraparound occurs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_xacts_left_before_wraparound{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ xid_from }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoints",
     "type": "graph",
     "description": "Total number of checkpoints occurred.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(postgres_checkpoints_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{ checkpoint }}"
      }
     ]
    },
    {
     "title": "Background Writes",
     "type": "graph",
     "description": "Total writes performed by background services or by backends implicitly.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(postgres_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{ process }}"
      },
      {
       "expr": "rate(postgres_wal_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "wal"
      },
      {
       "expr": "sum(rate(postgres_database_temp_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "tempfiles"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Usage",
     "type": "graph",
     "description": "Disk space usage by Postgres instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgres_tablespace_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ tablespace }}"
      },
      {
       "expr": "postgres_wal_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "wal"
      },
      {
       "expr": "postgres_log_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "log"
      }
     ]
    },
    {
     "title": "Databases",
     "type": "graph",
     "description": "Top databases by size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_database_size_bytes{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "graph",
     "description": "Top tables by size in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_table_size_bytes{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}.{{ schema }}.{{ table }}"
      }
     ]
    },
    {
     "title": "Indexes",
     "type": "graph",
     "description": "Top indexes by size in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_index_size_bytes{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}.{{ schema }}.{{ table }}.{{ index }}"
      }
     ]
    },
    {
     "title": "Databases Temporary Files",
     "type": "graph",
     "description": "Top databases by produced temporary files in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(postgres_database_temp_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Temporary Files in-flight",
     "type": "graph",
     "description": "Total size of active temporary files in-flight.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgres_temp_bytes_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ tablespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sequential Read, by rows",
     "type": "graph",
     "description": "The top-most tables which accessed sequentially.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_seq_tup_read_total{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Dead Tuples",
     "type": "graph",
     "description": "The top-most tables with dead tuples.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_table_tuples_dead_total{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "INSERTs",
     "type": "graph",
     "description": "The top-most tables with performed INSERTs per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_inserted_total{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "UPDATEs",
     "type": "graph",
     "description": "The top-most tables with performed UPDATEs (including HOT) per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_updated_total{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "DELETEs",
     "type": "graph",
     "description": "The top-most tables with performed DELETEs per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_deleted_total{database=~\"$database\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL Archiving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Archiving Lag, bytes",
     "type": "graph",
     "description": "Total amount of WAL segments (in bytes) which are not archived yet.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgres_archiver_lag_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "WAL Archiving, per minute",
     "type": "graph",
     "description": "Total amount of WAL segments processed per minute.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "increase(postgres_archiver_archived_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "archived"
      },
      {
       "expr": "increase(postgres_archiver_failed_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "WAL archiving settings",
     "type": "table",
     "description": "Important: when WAL archiving is disabled, metrics will not be collected.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"archive_.+\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "System Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * sum by (mode) (rate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\"}[1m])) / on (instance) group_left sum(rate(node_cpu_seconds_all_total{instance=\"$instance\"}[1m]))",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Storage Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (device) (rate(node_disk_time_seconds_total{instance=\"$instance\"}[1m])) / (sum by (device) (rate(node_disk_completed_total{instance=\"$instance\"}[1m])) + on() group_left vector(1))",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}