{
 "title": "Prometheus Mini",
 "description": "Dashboard providing insight to Prometheus monitoring system status and it's runtime info.",
 "tags": [
  "prometheus",
  "mini"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Observed instance",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   },
   { "name": "custom_label_name", "label": "Custom label name", "query": "job" },
   {
    "name": "custom_label_value",
    "label": "Custom label value",
    "query": {
     "query": "label_values(prometheus_build_info, $custom_label_name)"
    }
   },
   {
    "name": "aggregation_interval",
    "label": "Aggregation intarval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": {
     "query": "query_result({__name__=~\"prometheus_.*_seconds\"})"
    }
   },
   {
    "name": "long_term_interval",
    "query": "10m,30m,1h,6h,12h,1d,3d,1w,4w,12w,1y"
   },
   {
    "name": "rule",
    "label": "Rule",
    "query": "label_values(prometheus_rule_group_rules,rule_group)"
   }
  ]
 },
 "panels": [
  {
   "type": "table-old",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "max(prometheus_build_info{instance=~\"$instance\"}) by (instance, version)"
    },
    {
     "expr": "max(sum(prometheus_rule_group_rules{instance=~\"$instance\"}) by (instance) or prometheus_build_info{instance=~\"$instance\"}*0) by (instance)"
    },
    {
     "expr": "max(sum(prometheus_sd_discovered_targets{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", name=\"scrape\"}) by (instance,$custom_label_name) or prometheus_build_info{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}*0) by (instance,$custom_label_name)"
    },
    {
     "expr": "time() - max(prometheus_tsdb_lowest_timestamp_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    },
    {
     "expr": "min(prometheus_tsdb_storage_blocks_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    }
   ]
  },
  {
   "title": "Number of discovered targets per Type and config",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{instance=~\"$instance\", name=\"scrape\"}) by (instance,config,name)",
     "legendFormat": "{{config}}"
    }
   ]
  },
  {
   "title": "HTTP request count by handler in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_http_requests_total{instance=~\"$instance\"}[$aggregation_interval])) by (instance, handler) ",
     "legendFormat": " {{ handler }} handler on {{ instance }}"
    }
   ]
  },
  {
   "title": "$quantile quantile of HTTP request duration per handler",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_request_duration_seconds_bucket{instance=~\"$instance\"}[$aggregation_interval])) by (le,instance, handler))",
     "legendFormat": "{{ handler }} handler on {{instance}}/{{$custom_label_name}} "
    }
   ]
  },
  {
   "title": "$quantile of request size by handler",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_response_size_bytes_bucket{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (le,instance, handler)) > 0",
     "legendFormat": "{{ handler }} handler on {{ instance }}/{{ $custom_label_name }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
     "legendFormat": "CPU usage of {{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "Resident mem - размер страниц памяти, выделенных процессу операционной системой и в настоящее время находящихся в ОЗУ (RAM).\nTotal allocated - Общий объем памяти, используемый  приложением.",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "Resident memory"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\"})",
     "legendFormat": "Total allocated"
    }
   ]
  },
  {
   "title": "Percentage rule group evaluation duration from the rule group evaluation interval (top 20)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20,\nmax(prometheus_rule_group_last_duration_seconds{instance=~\"$instance\"}) by (rule_group, instance) /\nmin(prometheus_rule_group_interval_seconds{instance=~\"$instance\"}) by (rule_group, instance)\n)",
     "legendFormat": "Percentage of {{rule_group}} group evaluation interval on {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of rule evaulation duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_rule_evaluation_duration_seconds{instance=~\"$instance\", quantile=\"$quantile\"}) by (instance, quantile)",
     "legendFormat": "evaluation duration of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Allocations per second in $aggregation_interval",
   "type": "graph",
   "description": "Total number of bytes allocated, even if freed",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$aggregation_interval])",
     "legendFormat": "Allocated Bytes of {{instance}}"
    }
   ]
  },
  {
   "title": "Alert of notifictions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_notifications_sent_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sent notifications to {{alertmanager}} alertmanager from {{instance}}"
    }
   ]
  },
  {
   "title": "$quantile of notification latency per alertmanager",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(prometheus_notifications_latency_seconds{instance=~\"$instance\", quantile=\"$quantile\"}) by (instance,$custom_label_name, alertmanager)",
     "legendFormat": "Latency of notifications sent to {{alertmanager}} from  {{instance}}/{{$custom_label_name}}"
    }
   ]
  }
 ]
}