{
 "title": "Prometheus Full",
 "description": "Dashboard providing insight to Prometheus monitoring system status and it's runtime info.",
 "tags": [
  "prometheus",
  "full"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Observed instance",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   },
   { "name": "custom_label_name", "label": "Custom label name", "query": "job" },
   {
    "name": "custom_label_value",
    "label": "Custom label value",
    "query": {
     "query": "label_values(prometheus_build_info, $custom_label_name)"
    }
   },
   {
    "name": "aggregation_interval",
    "label": "Aggregation intarval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": {
     "query": "query_result({__name__=~\"prometheus_.*_seconds\"})"
    }
   },
   {
    "name": "long_term_interval",
    "query": "10m,30m,1h,6h,12h,1d,3d,1w,4w,12w,1y"
   }
  ]
 },
 "panels": [
  {
   "type": "table-old",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    },
    {
     "expr": "max(prometheus_build_info{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name, version)"
    },
    {
     "expr": "max(sum(prometheus_rule_group_rules{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name) or prometheus_build_info{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}*0) by (instance,$custom_label_name)"
    },
    {
     "expr": "max(sum(prometheus_sd_discovered_targets{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", name=\"scrape\"}) by (instance,$custom_label_name) or prometheus_build_info{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}*0) by (instance,$custom_label_name)"
    },
    {
     "expr": "time() - max(prometheus_tsdb_lowest_timestamp_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    },
    {
     "expr": "min(prometheus_tsdb_storage_blocks_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)"
    }
   ]
  },
  { "title": "Requests & queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "HTTP request count by handler in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_http_requests_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name, handler) ",
     "legendFormat": " {{ handler }} handler on {{ instance }}/{{ $custom_label_name }}"
    }
   ]
  },
  {
   "title": "$quantile quantile of HTTP request duration per handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_request_duration_seconds_bucket{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (le,instance, handler))",
     "legendFormat": "{{ handler }} handler on {{instance}}/{{$custom_label_name}} "
    }
   ]
  },
  {
   "title": "$quantile of request size by handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_response_size_bytes_bucket{instance=~\"$instance\"}[$aggregation_interval])) by (le,instance, handler)) > 0",
     "legendFormat": "{{ handler }} handler on {{ instance }}/{{ $custom_label_name }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
     "legendFormat": "CPU usage of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Resident mem - размер страниц памяти, выделенных процессу операционной системой и в настоящее время находящихся в ОЗУ (RAM). Total allocated - Общий объем памяти, используемый приложением.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
     "legendFormat": "Resident memory of {{instance}}/{{$custom_label_name}}"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (instance,$custom_label_name)",
     "legendFormat": "Total allocated bytes of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Allocations per second in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])",
     "legendFormat": "Allocated Bytes of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  { "title": "Rule evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Percentage rule group evaluation duration from the rule group evaluation interval (top 20)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20,\nmax(prometheus_rule_group_last_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (rule_group, instance) /\nmin(prometheus_rule_group_interval_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}) by (rule_group, instance)\n)\n",
     "legendFormat": "Percentage of {{rule_group}} group evaluation interval on {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of rule evaulation duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_rule_evaluation_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}) by (instance,$custom_label_name, quantile)",
     "legendFormat": "evaluation duration of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Number of rules per group (top 20 groups)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(topk(20,prometheus_rule_group_rules{instance=~\"$instance\", $custom_label_name=~\"$custom_label_value\"})) by (instance,$custom_label_name, rule_group)",
     "legendFormat": "number of rules in {{rule_group}} rule group on {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Notification queue size and capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_notifications_queue_length{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"})by (instance,$custom_label_name)",
     "legendFormat": "Queue size of {{instance}}/{{$custom_label_name}}"
    },
    {
     "expr": "sum(prometheus_notifications_queue_capacity{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"})by (instance,$custom_label_name)",
     "legendFormat": "Queue capacity of {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Number of sent notifictions per alertmanager in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_notifications_sent_total{instance=~\"$instance\"}[$__rate_interval])*45",
     "legendFormat": "Sent notifications to {{alertmanager}} alertmanager from {{instance}}"
    }
   ]
  },
  {
   "title": "$quantile of notification latency per alertmanager",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(prometheus_notifications_latency_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}) by (instance,$custom_label_name, alertmanager)",
     "legendFormat": "Latency of notifications sent to {{alertmanager}} from  {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  { "title": "Service discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Number of discovered targets per Type and config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", name=\"scrape\"}) by (instance,$custom_label_name,config,name)",
     "legendFormat": "Number of {{name}} type targets from config {{config}} on {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "Service discovery  sync count by mechanism in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_sd_refresh_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name,mechanism)",
     "legendFormat": "Number of sync for {{mechanism}} SD mechanism on {{instance}}/{{$custom_label_name}}"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
     "legendFormat": "Number of sync for consul SD mechanism on {{instance}}/{{$custom_label_name}}"
    },
    {
     "expr": "sum(increase(prometheus_sd_kubernetes_http_request_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}[$aggregation_interval])) by (instance,$custom_label_name)",
     "legendFormat": "Number of sync for kubernetes SD mechanism on {{instance}}/{{$custom_label_name}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of refresh duration per SD mechanism",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_sd_refresh_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}",
     "legendFormat": "Duration of sync for {{mechanism}} SD mechanism on {{instance}}/{{$custom_label_name}}"
    },
    {
     "expr": "consul_rpc_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}",
     "legendFormat": "Number of sync for consul SD mechanism on {{instance}}/{{$custom_label_name}}"
    },
    {
     "expr": "prometheus_sd_file_scan_duration_seconds{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\", quantile=\"$quantile\"}",
     "legendFormat": "Duration of sync for file_scan SD mechanism on {{instance}}/{{$custom_label_name}}"
    },
    {
     "expr": "prometheus_sd_kubernetes_http_request_duration_seconds_sum{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"} / prometheus_sd_kubernetes_http_request_duration_seconds_count{instance=~\"$instance\",$custom_label_name=~\"$custom_label_value\"}",
     "legendFormat": "AVG Duration of sync for k8s SD mechanism on {{instance}}/{{$custom_label_name}}"
    }
   ]
  }
 ]
}