{
 "title": "Vertx-Single",
 "description": "test",
 "tags": [
  "vertx",
  "mesh",
  "vertx-single"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vertx_pool_inUse{nodeName=\"Twinkling Nidorino\"}, instance)"
    }
   },
   {
    "name": "db_version",
    "query": {
     "query": "label_values(get_mesh_versions, db_version)"
    }
   },
   {
    "name": "db_vendor",
    "query": {
     "query": "label_values(get_mesh_versions, db_vendor)"
    }
   },
   {
    "name": "mesh_version",
    "query": {
     "query": "label_values(get_mesh_versions, mesh_version)"
    }
   },
   {
    "name": "search_vendor",
    "query": {
     "query": "label_values(get_mesh_versions, search_vendor)"
    }
   },
   {
    "name": "search_version",
    "query": {
     "query": "label_values(get_mesh_versions, search_version)"
    }
   },
   {
    "name": "vertx_version",
    "query": {
     "query": "label_values(get_mesh_versions, vertx_version)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(vertx_pool_inUse{nodeName=\"Twinkling Nidorino\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DB version/DB vendor",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; font-size: 2em\">$db_version/${db_vendor}</div>"
   },
   "targets": [
    {
     "expr": "get_mesh_versions{db_version=~\"$db_version\"}"
    }
   ]
  },
  {
   "title": "Mesh version",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; font-size: 2em\">$mesh_version</div>"
   }
  },
  {
   "title": "Search version/Search vendor",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; font-size: 2em\">$search_version/${search_vendor}</div>"
   }
  },
  {
   "title": "Vertx version",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; font-size: 2em\">$vertx_version</div>"
   }
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vertx_http_server_requestCount_total{instance=~\"$instance:$port\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Status from api/v2/status",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "get_mesh_status{instance=~\"$instance:$port\"}",
     "legendFormat": "api/v2/status"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_http_server_connections{instance=~\"$instance:$port\"}",
     "legendFormat": "{{local}}"
    }
   ]
  },
  {
   "title": "Request count rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total{instance=~\"$instance:$port\"}[1m])) by (code), 0.001)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request count rate by code and path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total{instance=~\"$instance:$port\"}[1m])) by (local,code,path), 0.001)"
    }
   ]
  },
  {
   "title": "Request rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vertx_http_server_requestCount_total{instance=~\"$instance:$port\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Global response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum{instance=~\"$instance:$port\"}[1m])) / sum(irate(vertx_http_server_responseTime_seconds_count{instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_responseTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    },
    {
     "expr": "sum(vertx_http_server_responseTime_seconds_max{instance=~\"$instance:$port\"}[1m])",
     "legendFormat": "[max]"
    }
   ]
  },
  {
   "title": "Response time by path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum{instance=~\"$instance:$port\"}[1m])) by (path) / sum(irate(vertx_http_server_responseTime_seconds_count{instance=~\"$instance:$port\"}[1m])) by (path)",
     "legendFormat": "{{path}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le,path))",
     "legendFormat": "{{path}} [med]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le,path))",
     "legendFormat": "{{path}} [99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesSent_sum{instance=~\"$instance:$port\"}[1m])) / sum(rate(vertx_http_server_bytesSent_count{instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesSent_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesSent_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesSent_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesReceived_sum{instance=~\"$instance:$port\"}[1m])) / sum(rate(vertx_http_server_bytesReceived_count{instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesReceived_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesReceived_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesReceived_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_eventbus_handlers{instance=~\"$instance:$port\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_eventbus_pending{instance=~\"$instance:$port\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: sent rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_sent_total{instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: received rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_received_total{instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum{instance=~\"$instance:$port\"}[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count{instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Eventbus processing time by address",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum{instance=~\"$instance:$port\"}[1m])) by (address) / sum(irate(vertx_eventbus_processingTime_seconds_count{instance=~\"$instance:$port\"}[1m])) by (address)",
     "legendFormat": "{{address}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le,address))",
     "legendFormat": "{{address}} [med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le,address))",
     "legendFormat": "{{address}} [95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket{instance=~\"$instance:$port\"}[1m])) by (le,address))",
     "legendFormat": "{{address}} [99p]"
    }
   ]
  },
  {
   "title": "Amount of invalidations of the whole cache",
   "type": "graph",
   "description": "Amount of invalidations of the whole cache",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_cache_projectname_clear_all_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectname: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_permission_clear_all_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_permission: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_projectbranchname_clear_all_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectbranchname: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_webroot_clear_all_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_webroot: {{instance}}"
    }
   ]
  },
  {
   "title": "Amount of cache hits/Amount of cache misses",
   "type": "graph",
   "description": "Amount of cache hits/Amount of cache misses",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_cache_projectname_miss_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectname_miss: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_permission_miss_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_permission_miss: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_projectbranchname_miss_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectbranchname_miss: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_webroot_miss_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_webroot_miss: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_webroot_hit_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_webroot_hit: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_projectbranchname_hit_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectbranchname_hit: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_permission_hit_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_permission_hit: {{instance}}"
    },
    {
     "expr": "increase(mesh_cache_projectname_hit_total{instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectname_hit: {{instance}}"
    }
   ]
  },
  {
   "title": "write lock timeouts",
   "type": "graph",
   "description": "Tracks the time which is spent waiting on the write lock/Amount of timeouts of acquiring the write lock",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesh_write_lock_timeout{instance=~\"$instance:$port\"}",
     "legendFormat": "write_lock_timeout: {{instance}}"
    },
    {
     "expr": "increase(mesh_write_lock_waiting_time_seconds_count{instance=~\"$instance:$port\"})",
     "legendFormat": "write_lock_waiting_time: {{instance}}"
    },
    {
     "expr": "increase(mesh_topology_lock_waiting_time_seconds_count{instance=~\"$instance:$port\"})",
     "legendFormat": "topology_lock_waiting_time: {{instance}}"
    },
    {
     "expr": "mesh_topology_lock_timeout{instance=~\"$instance:$port\"}",
     "legendFormat": "topology_lock_timeout: {{instance}}"
    }
   ]
  }
 ]
}