{
 "title": "Vertx-Cluster",
 "description": "test",
 "tags": [
  "vertx",
  "mesh",
  "vertx-cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(get_mesh_cluster_status{job=\"mesh_status_cluster\"}, instance)"
    }
   },
   {
    "name": "db_version",
    "query": {
     "query": "label_values(get_mesh_cluster_versions, db_version)"
    }
   },
   {
    "name": "db_vendor",
    "query": {
     "query": "label_values(get_mesh_cluster_versions, db_vendor)"
    }
   },
   {
    "name": "mesh_version",
    "query": {
     "query": "label_values(get_mesh_cluster_versions, mesh_version)"
    }
   },
   {
    "name": "search_vendor",
    "query": {
     "query": "label_values(get_mesh_cluster_versions, search_vendor)"
    }
   },
   {
    "name": "search_version",
    "query": {
     "query": "label_values(get_mesh_cluster_versions, search_version)"
    }
   },
   {
    "name": "vertx_version",
    "query": {
     "query": "label_values(get_mesh_cluster_versions, vertx_version)"
    }
   },
   {
    "name": "clusterName",
    "label": "ClusterName",
    "query": {
     "query": "label_values(vertx_pool_inUse, clusterName)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(get_mesh_cluster_versions, job)"
    }
   },
   {
    "name": "nodeexporterport",
    "label": "NodeExporterPort",
    "query": {
     "query": "label_values(node_cpu_seconds_total{job=\"nodeexporter\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(get_mesh_cluster_status{job=\"mesh_status_cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mesh status",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "get_mesh_cluster_versions{job=\"mesh_cluster_versions\",instance=~\"$instance:$port\"}"
    },
    {
     "expr": "get_mesh_cluster_status{job=\"mesh_cluster_versions\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_http_server_connections{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}",
     "legendFormat": "{{instance}},{{local}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "Request count rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(vertx_http_server_requestCount_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (code), 0.001)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request count rate by code and path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(vertx_http_server_requestCount_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (local,code,path), 0.001)",
     "legendFormat": "{{local}},{{code}},{{path}}"
    }
   ]
  },
  {
   "title": "Request rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vertx_http_server_requestCount_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Global response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) / sum(irate(vertx_http_server_responseTime_seconds_count{clusterName=~\"$clusterName\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(vertx_http_server_responseTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(vertx_http_server_responseTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(vertx_http_server_responseTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Response time by path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (path) / sum(irate(vertx_http_server_responseTime_seconds_count{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (path)",
     "legendFormat": "{{path}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(vertx_http_server_responseTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le,path))",
     "legendFormat": "{{path}} [med]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(vertx_http_server_responseTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le,path))",
     "legendFormat": "{{path}} [99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesSent_sum{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) / sum(rate(vertx_http_server_bytesSent_count{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesSent_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesSent_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesSent_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesReceived_sum{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) / sum(rate(vertx_http_server_bytesReceived_count{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesReceived_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesReceived_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesReceived_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_eventbus_handlers{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_eventbus_pending{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: sent rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_sent_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: received rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_received_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Eventbus processing time by address",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (address) / sum(irate(vertx_eventbus_processingTime_seconds_count{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (address)",
     "legendFormat": "{{address}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le,address))",
     "legendFormat": "{{address}} [med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le,address))",
     "legendFormat": "{{address}} [95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}[1m])) by (le,address))",
     "legendFormat": "{{address}} [99p]"
    }
   ]
  },
  {
   "title": "Amount of invalidations of the whole cache",
   "type": "graph",
   "description": "Amount of invalidations of the whole cache",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_cache_projectname_clear_all_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectname: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_permission_clear_all_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_permission: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_projectbranchname_clear_all_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectbranchname: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_webroot_clear_all_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_webroot: {{instance}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "Amount of cache hits/Amount of cache misses",
   "type": "graph",
   "description": "Amount of cache hits/Amount of cache misses",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_cache_projectname_miss_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectname_miss: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_permission_miss_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_permission_miss: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_projectbranchname_miss_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectbranchname_miss: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_webroot_miss_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_webroot_miss: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_webroot_hit_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_webroot_hit: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_projectbranchname_hit_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectbranchname_hit: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_permission_hit_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_permission_hit: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_cache_projectname_hit_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "cache_projectname_hit: {{instance}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "write lock timeouts",
   "type": "graph",
   "description": "Tracks the time which is spent waiting on the write lock/Amount of timeouts of acquiring the write lock",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesh_write_lock_timeout{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}",
     "legendFormat": "write_lock_timeout: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_write_lock_waiting_time_seconds_count{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "write_lock_waiting_time: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_topology_lock_waiting_time_seconds_count{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "topology_lock_waiting_time: {{instance}},{{nodeName}}"
    },
    {
     "expr": "mesh_topology_lock_timeout{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"}",
     "legendFormat": "topology_lock_timeout: {{instance}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "graphql requests",
   "type": "graph",
   "description": "Timer which tracks duration of graphql requests",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_graphql_time_seconds_count{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "{{instance}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "tx/notx_created",
   "type": "graph",
   "description": "Meter which measures the rate of created transactions over time/Meter which measures the rate of created noTx transactions over time",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_tx_created_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "tx: {{instance}},{{nodeName}}"
    },
    {
     "expr": "increase(mesh_notx_created_total{clusterName=~\"$clusterName\",instance=~\"$instance:$port\"})",
     "legendFormat": "notx: {{instance}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"} - node_memory_MemFree_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"} - (node_memory_Cached_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"} + node_memory_Buffers_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"} + node_memory_Buffers_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"} - node_memory_SwapFree_bytes{instance=~\"$instance:$nodeexporterport\",job=\"nodeexporter\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  }
 ]
}