{
 "title": "Storage capacity",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(ceph_health_status, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total data stored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_stored)" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{namespace =~ \"$cluster\"}-ceph_cluster_total_used_bytes{namespace =~ \"$cluster\"})/ceph_cluster_total_bytes{namespace =~ \"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total RAW data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_raw_bytes{namespace =~ \"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data stored",
   "type": "piechart",
   "description": "The actual data stored in the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_pool_stored{namespace =~ \"$cluster\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{namespace =~ \"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAW data (with redundancy)",
   "type": "piechart",
   "description": "The actual data stored in the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_pool_stored_raw{namespace =~ \"$cluster\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{namespace =~ \"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}