{
 "title": "Ceph S3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(ceph_rgw_qlen, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ceph_rgw_qlen{namespace=\"$cluster\"}, instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_rgw_qlen{namespace=\"$cluster\", instance_id=~\"$instance\"}",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "RGW Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ceph_rgw_cache_hit{namespace=\"$cluster\", instance_id=~\"$instance\"}[1m])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "RGW Cache Miss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ceph_rgw_cache_miss{namespace=\"$cluster\", instance_id=~\"$instance\"}[1m])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "RGW gets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ceph_rgw_get{namespace=\"$cluster\", instance_id=~\"$instance\"}[1m])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "RGW puts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ceph_rgw_put{namespace=\"$cluster\", instance_id=~\"$instance\"}[1m])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "RGW Failed Req",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ceph_rgw_failed_req{namespace=\"$cluster\", instance_id=~\"$instance\"}[1m])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  }
 ]
}