{
 "title": "Ceph - RBD",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,10m,30m,1h" },
   {
    "name": "cluster",
    "query": "label_values(ceph_health_status, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "RBD IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RBD read bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rbd_read_bytes{namespace=\"$cluster\"}[1m])",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "RBD write bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rbd_write_bytes{namespace=\"$cluster\"}[1m])",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "RBD read iops",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rbd_read_ops{namespace=\"$cluster\"}[1m])",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "RBD write iops",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rbd_write_ops{namespace=\"$cluster\"}[1m])",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}