{
 "title": "Cluster summary NRP",
 "description": "Cluster usage by namespace.",
 "tags": [
  "GPU",
  "CPU",
  "Memory"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Quick Links",
   "type": "text",
   "description": "Links to the  information about namespaces",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"http://ucsd-prp.gitlab.io/nautilus/namespaces\" target=\"_blank\">Nautilus cluster namespaces</a>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Installed  GPUs",
   "type": "stat",
   "description": "Total number of GPUs in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (DCGM_FI_DEV_GPU_TEMP * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"})"
    }
   ]
  },
  {
   "title": "GPU usage by namespace",
   "type": "piechart",
   "description": "Number of free and used by a specific namespace GPUs as a fraction of total available",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (DCGM_FI_DEV_GPU_TEMP * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"}) by (namespace)",
     "legendFormat": "{{namespace_name}}"
    }
   ]
  },
  {
   "title": "Requested GPUs average  utilization (%) by namespace",
   "type": "timeseries",
   "description": "Requested GPU utilization %  as an average over  all pods run in a specific namespace",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"}) by (namespace) / count (DCGM_FI_DEV_GPU_UTIL * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Allocated GPUs",
   "type": "stat",
   "description": "Number of GPUs currently assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " count (DCGM_FI_DEV_GPU_TEMP{namespace!=\"\"} * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"})"
    }
   ]
  },
  {
   "title": "Average GPU usage",
   "type": "gauge",
   "description": "Average GPU utilization % for  GPUs currently  assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(DCGM_FI_DEV_GPU_UTIL{namespace!=\"\"} * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"}) / count (DCGM_FI_DEV_GPU_UTIL{namespace!=\"\"} * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"}))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Installed CPUs",
   "type": "stat",
   "description": "Number of CPU cores  in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"})"
    }
   ]
  },
  {
   "title": "CPU usage by namespace",
   "type": "piechart",
   "description": "Number of free and used by a specific namespace CPUs as a fraction of total available",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"}) > 1",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(container, pod, namespace) group_right kube_pod_container_status_running) - sum(sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"}))",
     "legendFormat": "Requested but not used"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"}) - sum(sum by(container, pod, namespace) (kube_pod_container_resource_requests{resource=\"cpu\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"})  * on(container, pod, namespace) group_right kube_pod_container_status_running)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU usage by namespace",
   "type": "timeseries",
   "description": "CPU usage  by a namespace as a per-second rate of CPU requests (as measured over the last 5 minutes)",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"}) >=1",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Allocated  CPUs",
   "type": "stat",
   "description": "Number of CPUs currently assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum by(container, pod, namespace) (kube_pod_container_resource_requests{resource=\"cpu\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"})  * on(container, pod, namespace) group_right kube_pod_container_status_running)"
    }
   ]
  },
  {
   "title": "Used  CPUs",
   "type": "stat",
   "description": "Number of CPUs currently assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Installed Memory (TB)",
   "type": "stat",
   "description": "Total  TB of available memory in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum (kube_node_status_capacity{resource=\"memory\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"})"
    }
   ]
  },
  {
   "title": "Memory usage (GB)  by namespace",
   "type": "piechart",
   "description": "Free memory  and  memory used by a specific namespace as a fraction  (and %) of total available.",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(namespace) (container_memory_rss{container!=\"\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"}))  >= 5000000000",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "(sum (kube_node_status_capacity{resource=\"memory\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"}) - sum(sum by(namespace) (kube_pod_container_resource_requests{resource=\"memory\",  node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"})))",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum (kube_pod_container_resource_requests{resource=\"memory\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(container, pod, namespace) group_right kube_pod_container_status_running) - sum(sum by(namespace) (container_memory_rss{container!=\"\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"})))",
     "legendFormat": "Requested but not used"
    }
   ]
  },
  {
   "title": "Memory usage  (GB) by namespace",
   "type": "timeseries",
   "description": "Memory  (GB) used  by  a specific namespaces",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": " sum by(namespace) (container_memory_rss{container!=\"\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"}) >= 5000000000",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Allocated memory (TB)",
   "type": "stat",
   "description": "Memory (TB) currently used  by the namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (sum by(container, pod, namespace) (kube_pod_container_resource_requests{resource=\"memory\",  node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"}) * on(container, pod, namespace) group_right kube_pod_container_status_running)"
    }
   ]
  },
  {
   "title": "Used memory (TB)",
   "type": "stat",
   "description": "Memory (TB) currently used  by the namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum by(namespace) (container_memory_rss{container!=\"\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"}))"
    }
   ]
  },
  { "title": "FPGAs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Installed FPGAs",
   "type": "stat",
   "description": "Number of FPGAs  in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=~\"amd.com.*\",node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"})"
    }
   ]
  },
  {
   "title": "FPGA use by namespace",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(namespace) (kube_pod_container_resource_requests{resource=~\"amd.com.*\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "FPGA usage by namespace",
   "type": "timeseries",
   "description": "FPGA used  by  a specific namespaces",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by(namespace) (kube_pod_container_resource_requests{resource=~\"amd.com.*\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"} * on(namespace, pod) group_left() kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Allocated  FPGAs",
   "type": "stat",
   "description": "Number of FPGAs currently assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum by(container, pod, namespace) (kube_pod_container_resource_requests{resource=~\"amd.com.*\", node=~\"node-.*.sdsc.optiputer.net|hcc-nrp-shor-c.*.unl.edu|gpu-.*.nrp.mghpcc.org\"})  * on(container, pod, namespace) group_right kube_pod_container_status_running)"
    }
   ]
  }
 ]
}