{
 "title": "Cluster usage",
 "description": "Cluster usage by namespace.",
 "tags": [
  "GPU",
  "CPU",
  "Memory"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Quick Links",
   "type": "text",
   "description": "Links to the  information about namespaces",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"http://ucsd-prp.gitlab.io/nautilus/namespaces\" target=\"_blank\">Nautilus cluster namespaces</a>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Installed  GPUs",
   "type": "stat",
   "description": "Total number of GPUs in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(DCGM_FI_DEV_GPU_TEMP)" }
   ]
  },
  {
   "title": "GPU usage by namespace",
   "type": "piechart",
   "description": "Number of free and used by a specific namespace GPUs as a fraction of total available",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_TEMP) by (namespace)",
     "legendFormat": "{{namespace_name}}"
    }
   ]
  },
  {
   "title": "Requested GPUs average  utilization (%) by namespace",
   "type": "timeseries",
   "description": "Requested GPU utilization %  as an average over  all pods run in a specific namespace",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{namespace != \"\"}) by (namespace) > 0",
     "legendFormat": "{{namespace_name}}"
    }
   ]
  },
  {
   "title": "Allocated GPUs",
   "type": "stat",
   "description": "Number of GPUs currently assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_TEMP{namespace!=\"\"})"
    }
   ]
  },
  {
   "title": "Average GPU usage",
   "type": "gauge",
   "description": "Average GPU utilization % for  GPUs currently  assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{namespace != \"\"}) "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Installed CPUs",
   "type": "stat",
   "description": "Number of CPU cores  in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",node !~ \"admiralty.*\"})"
    }
   ]
  },
  {
   "title": "CPU usage by namespace",
   "type": "piechart",
   "description": "Number of free and used by a specific namespace CPUs as a fraction of total available",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "namespace_cpu_usage > 1", "legendFormat": "{{namespace}}" },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(container, pod, namespace) group_right kube_pod_container_status_running) - sum(namespace_cpu_usage)",
     "legendFormat": "Requested but not used"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",node !~ \"admiralty.*\"}) - sum(sum by(container, pod, namespace) (kube_pod_container_resource_requests{resource=\"cpu\"})  * on(container, pod, namespace) group_right kube_pod_container_status_running)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU usage by namespace",
   "type": "timeseries",
   "description": "CPU usage  by a namespace as a per-second rate of CPU requests (as measured over the last 5 minutes)",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "namespace_cpu_usage >=1", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Allocated  CPUs",
   "type": "stat",
   "description": "Number of CPUs currently assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum by(container, pod, namespace) (kube_pod_container_resource_requests{resource=\"cpu\"})  * on(container, pod, namespace) group_right kube_pod_container_status_running)"
    }
   ]
  },
  {
   "title": "Used  CPUs",
   "type": "stat",
   "description": "Number of CPUs currently assigned to the pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(namespace_cpu_usage)" }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Installed Memory (TB)",
   "type": "stat",
   "description": "Total  TB of available memory in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum (kube_node_status_capacity{resource=\"memory\", node !~ \"admiralty.*\"}) / 1024^4"
    }
   ]
  },
  {
   "title": "Memory usage (GB)  by namespace",
   "type": "piechart",
   "description": "Free memory  and  memory used by a specific namespace as a fraction  (and %) of total available.",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(namespace_memory_usage / 1024^3)  >=5",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "(sum (kube_node_status_capacity{resource=\"memory\", node !~ \"admiralty.*\"}) - sum(namespace_memory_usage)) / 1024^3",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum (kube_pod_container_resource_requests{resource=\"memory\"} * on(container, pod, namespace) group_right kube_pod_container_status_running) - sum(namespace_memory_usage))  / 1024^3",
     "legendFormat": "Requested but not used"
    }
   ]
  },
  {
   "title": "Memory usage  (GB) by namespace",
   "type": "timeseries",
   "description": "Memory  (GB) used  by  a specific namespaces",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namespace_memory_usage / 1024^3  >=5",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Allocated memory (TB)",
   "type": "stat",
   "description": "Memory (TB) currently used  by the namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (sum by(container, pod, namespace) (kube_pod_container_resource_requests{resource=\"memory\"}) * on(container, pod, namespace) group_right kube_pod_container_status_running) / 1024^4"
    }
   ]
  },
  {
   "title": "Used memory (TB)",
   "type": "stat",
   "description": "Memory (TB) currently used  by the namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory_usage / 1024^3)"
    }
   ]
  }
 ]
}