{
 "title": "K8s / Compute Resources / Namespace GPUs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current GPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"})/count(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total GPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(namespace_gpu_utilization{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "Namespace GPU usage"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requested GPUs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_TEMP{namespace=~\"$namespace\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPUs utilization % by pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}) by (pod) / count(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_TEMP{namespace=~\"$namespace\"}) by (pod, modelName)"
    },
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}) by (pod) / count(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}) by (pod)"
    }
   ]
  }
 ]
}