{
 "title": "K8s / Compute Resources / Cluster GPUs",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total GPUs",
   "type": "stat",
   "description": "The total number of Nvidia GPU cards in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(namespace_gpu_usage)" }
   ]
  },
  {
   "title": "Used GPUs",
   "type": "stat",
   "description": "The total number of Nvidia GPU cards requested",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(namespace_gpu_usage{namespace!=\"gpu-mon\"})"
    }
   ]
  },
  {
   "title": "Requested GPUs %",
   "type": "gauge",
   "description": "Amount of GPUs requested",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count (DCGM_FI_DEV_GPU_UTIL{namespace!=\"gpu-mon\"})*100/sum(namespace_gpu_usage)"
    }
   ]
  },
  {
   "title": "Requested utilization",
   "type": "gauge",
   "description": "current utilization of the requested GPUs",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(DCGM_FI_DEV_GPU_UTIL{namespace!=\"gpu-mon\"}) / count (DCGM_FI_DEV_GPU_UTIL{namespace!=\"gpu-mon\"}))"
    }
   ]
  },
  {
   "title": "Total utilization",
   "type": "gauge",
   "description": "current total utilization of the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(DCGM_FI_DEV_GPU_UTIL) / count (DCGM_FI_DEV_GPU_UTIL))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of requested GPUs by namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namespace_gpu_usage",
     "legendFormat": "{{namespace_name}} {{exported_namespace}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requested GPUs utilization % by namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL) by (namespace) / count (DCGM_FI_DEV_GPU_UTIL) by (namespace)",
     "legendFormat": "{{namespace_name}}"
    }
   ]
  },
  {
   "title": "Current stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "namespace_gpu_usage" },
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL) by (namespace) / count (DCGM_FI_DEV_GPU_UTIL) by (namespace)"
    }
   ]
  }
 ]
}