{
 "title": "K8s / Compute Resources / Cluster GPUs A100",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total A100 GPUs",
   "type": "stat",
   "description": "The total number of Nvidia GPU cards in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(DCGM_FI_DEV_GPU_TEMP{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}))"
    }
   ]
  },
  {
   "title": "Used A100 GPUs",
   "type": "stat",
   "description": "The total number of Nvidia GPU cards requested",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(count(DCGM_FI_DEV_GPU_TEMP{namespace!=\"gpu-mon\", modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}))"
    }
   ]
  },
  {
   "title": "Requested A100 GPUs %",
   "type": "gauge",
   "description": "Amount of GPUs requested",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count (DCGM_FI_DEV_GPU_UTIL{namespace!=\"gpu-mon\", modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"})*100/sum(count (DCGM_FI_DEV_GPU_TEMP{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}))"
    }
   ]
  },
  {
   "title": "Requested A100 utilization",
   "type": "gauge",
   "description": "current utilization of the requested GPUs",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(DCGM_FI_DEV_GPU_UTIL{namespace!=\"gpu-mon\",modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}) / count (DCGM_FI_DEV_GPU_UTIL{namespace!=\"gpu-mon\", modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}))"
    }
   ]
  },
  {
   "title": "Total A100 utilization",
   "type": "gauge",
   "description": "current total utilization of the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(DCGM_FI_DEV_GPU_UTIL{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}) / count (DCGM_FI_DEV_GPU_UTIL{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of requested A100 GPUs by namespace (gpu-mon=unused)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (namespace) (DCGM_FI_DEV_GPU_TEMP{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"})",
     "legendFormat": "{{namespace_name}} {{exported_namespace}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requested A100 GPUs utilization % by namespace (gpu-mon=unused)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}) by (namespace) / count (DCGM_FI_DEV_GPU_UTIL{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}) by (namespace)",
     "legendFormat": "{{namespace_name}}"
    }
   ]
  },
  {
   "title": "Current stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "A100 GPU usage (gpu-mon=unused)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (namespace) (DCGM_FI_DEV_GPU_TEMP{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"})"
    },
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}) by (namespace) / count (DCGM_FI_DEV_GPU_UTIL{modelName=~\"NVIDIA A100.*\", GPU_I_ID=\"\"}) by (namespace)"
    }
   ]
  }
 ]
}