{
 "title": "GPUs usage",
 "description": "GPU requests",
 "tags": [
  "GPU",
  "Nvidia"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total GPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"})"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"})/sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"})"
    }
   ]
  },
  {
   "title": "GPUs capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance, pod)(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Free GPUs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance, pod)(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) - on(node) \n  (sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(node) or on(node) avg without(instance, pod)(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"})*0)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "GPU requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}",
     "legendFormat": "{{namespace}}/{{pod}}@{{node}}"
    }
   ]
  }
 ]
}