{
 "title": "HAProxy Ingress",
 "tags": [
  "haproxy",
  "ingress-controller",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(haproxy_frontend_sessions_total,pod)"
    }
   },
   {
    "name": "backend",
    "query": {
     "query": "label_values(haproxy_backend_sessions_total,proxy)"
    }
   },
   {
    "name": "public_frontend",
    "query": "(_tcp_.*|_front_http|_front[0-9]*)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HAProxy proc use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100*max(rate(haproxyingress_haproxy_processing_seconds_total{pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "HAProxy running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(haproxyingress_update_success{pod=~\"$pod\"})-count(haproxy_process_start_time_seconds{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Current sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*max(sum(haproxy_frontend_current_sessions{pod=~\"$pod\"}) by (hostname)/max(haproxy_process_max_connections{pod=~\"$pod\"}) by (hostname))"
    }
   ]
  },
  {
   "title": "Connections / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$public_frontend\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "HAProxy threads p/proc",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(haproxy_process_nbthread{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "HAProxy uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max(haproxy_process_start_time_seconds{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Reload successful",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(haproxyingress_update_success{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Certificate expiring",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(min(haproxyingress_cert_expire_date_epoch)-time())/3600/24"
    }
   ]
  },
  {
   "title": "HTTP request rate / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"(_front[0-9]+|_front_http)\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Controller instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(haproxyingress_update_success{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Controller uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max(process_start_time_seconds{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "HAProxy process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HAProxy process use",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*rate(haproxyingress_haproxy_processing_seconds_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Admin socket response time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxyingress_haproxy_response_time_seconds_sum{pod=~\"$pod\",command=\"show_info\"}[1m])/rate(haproxyingress_haproxy_response_time_seconds_count{pod=~\"$pod\",command=\"show_info\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Full reloads (1m)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(haproxyingress_updates_total{pod=~\"$pod\",status=\"full\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Admin socket response time above 10ms",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100-(100*increase(haproxyingress_haproxy_response_time_seconds_bucket{pod=~\"$pod\",command=\"show_info\",le=\"0.01\"}[1m]) / ignoring (le) increase(haproxyingress_haproxy_response_time_seconds_count{pod=~\"$pod\",command=\"show_info\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*rate(process_cpu_seconds_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "{{pod}} | {{job}}"
      }
     ]
    },
    {
     "title": "Controller sync rate (1m)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(haproxyingress_updates_total{pod=~\"$pod\"}[1m])) by (hostname)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connection rate (conn/s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$public_frontend\",pod=~\"$pod\"}[1m])) by (hostname)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "HTTP request/response rate (req/s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"(_front[0-9]+|_front_http)\",pod=~\"$pod\"}[1m])) by (hostname)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current sessions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_frontend_current_sessions{pod=~\"$pod\"}) by (hostname)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current sessions / max",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*sum(haproxy_frontend_current_sessions{pod=~\"$pod\"}) by (hostname)/min(haproxy_process_max_connections{pod=~\"$pod\"}) by (hostname)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cluster wide bytes in/out rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$public_frontend\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "in"
      },
      {
       "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$public_frontend\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "Bytes in/out rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$public_frontend\",pod=~\"$pod\"}[1m])) by (hostname)",
       "legendFormat": "{{pod}} in"
      },
      {
       "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$public_frontend\",pod=~\"$pod\"}[1m])) by (hostname)",
       "legendFormat": "{{pod}} out"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top 5 4xx responses / minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(increase(haproxy_backend_http_responses_total{pod=~\"$pod\",proxy=~\"$backend\",code=\"4xx\"}[1m])) by (proxy,code))",
       "legendFormat": "{{code}} - {{proxy}}"
      }
     ]
    },
    {
     "title": "Top 5 5xx responses / minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(increase(haproxy_backend_http_responses_total{pod=~\"$pod\",proxy=~\"$backend\",code=~\"5xx|other\"}[1m])) by (proxy,code))",
       "legendFormat": "{{code}} - {{proxy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top 5 request/response rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(rate(haproxy_backend_http_responses_total{pod=~\"$pod\",proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Top 5 bytes in/out rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk(5,sum(rate(haproxy_backend_bytes_in_total{pod=~\"$pod\",proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}} in"
      },
      {
       "expr": "topk(5,sum(rate(haproxy_backend_bytes_out_total{pod=~\"$pod\",proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}} out"
      }
     ]
    },
    {
     "title": "Top 5 max/avg connection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5,max(haproxy_backend_connect_time_average_seconds{pod=~\"$pod\",proxy=~\"$backend\"}) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Top 5 current sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(haproxy_backend_current_sessions{pod=~\"$pod\",proxy=~\"$backend\"}) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Certificate signing failures",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(haproxyingress_cert_signing_count{pod=~\"$pod\",success=\"false\"}[1m])) by (hostname,domains)",
       "legendFormat": "{{pod}} | {{domains}}"
      }
     ]
    },
    {
     "title": "New certificates issued",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(haproxyingress_cert_signing_count{pod=~\"$pod\",reason=\"missing\",success=\"true\"}[1m])) by (hostname)",
       "legendFormat": "{{pod}} | missing"
      },
      {
       "expr": "sum(increase(haproxyingress_cert_signing_count{pod=~\"$pod\",reason=\"expiring\",success=\"true\"}[1m])) by (hostname)",
       "legendFormat": "{{pod}} | expiring"
      },
      {
       "expr": "sum(increase(haproxyingress_cert_signing_count{pod=~\"$pod\",reason=\"outdated\",success=\"true\"}[1m])) by (hostname)",
       "legendFormat": "{{pod}} | outdated"
      }
     ]
    },
    {
     "title": "Certificate expiration",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "min(1000*haproxyingress_cert_expire_date_epoch{pod=~\"$pod\"}) by (cn)"
      }
     ]
    }
   ]
  }
 ]
}