{
 "title": "IPMI Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1s,5s,1m,5m,10m,30m,1h,3h,6h,12h,1d,2d,3d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "query_result(ipmi_temperatures * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperatures{sensor=~\"CPU[0-9]?( Temp|_TEMP)\"}  * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$host\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_voltages{sensor=~\"Vcpu[0-9]?\"} * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$host\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "ipmi_fan_speed * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$host\"}",
     "legendFormat": "{{ fan }}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperatures{sensor =~ \"P?[0-9]?-?DIMM[A-Z]+[0-9]+( Temp|_TEMP)\"} * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$host\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "All Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperatures * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$host\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "All Voltages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_voltages * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$host\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  }
 ]
}