{
 "title": "K8S Nvidia GPU - Cluster",
 "description": "Per Host Nvidia GPU",
 "tags": [
  "Nvidia",
  "GPU",
  "kubernetes",
  "cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "query_result(DCGM_FI_DEV_GPU_TEMP * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GPU memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1-sum(nvml_memory_free)/sum(nvml_memory_total)"
      }
     ]
    },
    {
     "title": "Total GPU memory",
     "type": "stat",
     "description": "The total Nvidia GPU memory size.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(nvml_memory_total)" }
     ]
    },
    {
     "title": "Available GPU memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(nvml_memory_free)" }
     ]
    },
    {
     "title": "Used GPU memory",
     "type": "stat",
     "description": "The used Nvidia GPU memory size.",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(nvml_memory_used)" }
     ]
    },
    {
     "title": "Total GPUs",
     "type": "stat",
     "description": "The total number of Nvidia GPU cards in the cluster",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(nvml_gpu_percent)" }
     ]
    },
    {
     "title": "Total Hosts",
     "type": "stat",
     "description": "Total hosts in the cluster",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(nvml_up)" }
     ]
    }
   ]
  },
  {
   "title": "Cluster utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total utilization",
     "type": "gauge",
     "description": "current total utilization of the cluster.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(sum(nvml_gpu_percent) by (instance, device_id))"
      }
     ]
    },
    {
     "title": "Total GPU utilization",
     "type": "graph",
     "description": "Total GPU usage of all hosts",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum( sum(nvml_gpu_percent * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) by (node, device_id)) by (node)  / count(nvml_gpu_percent * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) by(node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$host\"}) / count(DCGM_FI_DEV_GPU_UTIL * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$host\"})",
     "legendFormat": "Utilization"
    }
   ]
  }
 ]
}