{
 "title": "Requests stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU cores",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace!~\"elastiflow|elastic-system|gpu-mon|guacamole|inmonts|ipmi|kconmon|kube-system|kubeless|metallb-system|monitoring|nextcloud|netbox|osg-jupyter|perfsonar|rook|rook-east|rook-haosu|rook-system|rook-suncave|suncave|squid|tstat|ucm-wave|kraken\", resource=\"cpu\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace!~\"elastiflow|elastic-system|gpu-mon|guacamole|inmonts|ipmi|kconmon|kube-system|kubeless|metallb-system|monitoring|nextcloud|netbox|osg-jupyter|perfsonar|rook|rook-east|rook-haosu|rook-system|rook-suncave|suncave|squid|tstat|ucm-wave|kraken\", resource=\"memory\"}"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\", namespace!~\"elastiflow|elastic-system|gpu-mon|guacamole|inmonts|ipmi|kconmon|kube-system|kubeless|metallb-system|monitoring|nextcloud|netbox|osg-jupyter|perfsonar|rook|rook-east|rook-haosu|rook-system|rook-suncave|suncave|squid|tstat|ucm-wave|kraken\"}"
    }
   ]
  }
 ]
}