{
 "title": "Utilization by namespace",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requested GPUs utilization % by namespace",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(namespace_gpu_utilization[10m])",
     "legendFormat": "{{namespace_name}}"
    }
   ]
  },
  {
   "title": "Requested CPUs utilization % by namespace",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(namespace_cpu_utilization[10m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Requested memory utilization % by namespace",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(namespace_memory_utilization[10m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}