---
## Here we are going to use self-signed certificates for Transport (Node-Node communication) & REST API layer
## Using searchguard offline TLS tool to create node & root certificates
- name: Clear local temporary directory for certificates
  local_action:
    module: file
    path: /tmp/opendistro-nodecerts
    state: absent
  run_once: true

- name: Create local temporary directory for certificates generation
  local_action:
    module: file
    path: /tmp/opendistro-nodecerts
    state: directory
  run_once: true

- name: Create subdirectory for certificates generation
  local_action:
    module: file
    path: "/tmp/opendistro-nodecerts/{{ item.path }}"
    state: directory
  run_once: true
  with_items:
    - { path: 'tools' }
    - { path: 'config' }

- name: Copy certificates generation tool
  local_action:
    module: copy
    src: 'search-guard-tlstool-1.5.zip'
    dest: /tmp/opendistro-nodecerts/search-guard-tlstool.zip
  run_once: true

- name: Extract the certificates generation tool
  local_action: 
    module: unarchive
    src: /tmp/opendistro-nodecerts/search-guard-tlstool.zip
    dest: /tmp/opendistro-nodecerts/
    remote_src: yes
  run_once: true

- name: Make the executable file
  local_action:
    module: file
    dest: /tmp/opendistro-nodecerts/tools/sgtlstool.sh
    mode: a+x
  run_once: true

- name: Prepare the certificates generation template file
  local_action:
    module: template
    src: tlsconfig.yml.j2
    dest: /tmp/opendistro-nodecerts/config/tlsconfig.yml
 
- name: Generate the node & admin certificates in local
  local_action:
    module: command /tmp/opendistro-nodecerts/tools/sgtlstool.sh -c /tmp/opendistro-nodecerts/config/tlsconfig.yml -ca -crt -t /tmp/opendistro-nodecerts/config/
  run_once: true

- name: Copy node, root and admin certificates
  copy:
    src: "/tmp/opendistro-nodecerts/config/{{ item }}"
    dest: "{{ odfe_data_dir }}/certs"
    owner: '1000'
    mode: 0600
  with_items:
    - "opensearch-node-{{ ansible_hostname }}.key"
    - "opensearch-node-{{ ansible_hostname }}.pem"
    - "opensearch-node-{{ ansible_hostname }}_http.key"
    - "opensearch-node-{{ ansible_hostname }}_http.pem"
    - "{{ ansible_hostname }}-kibana_http.pem"
    - "{{ ansible_hostname }}-kibana_http.key"
    - admin.key
    - admin.pem
    - root-ca.pem
    - root-ca.key

- name: Remove local temporary directory for certificates generation
  local_action:
    module: file
    path: /tmp/opendistro-nodecerts
    state: absent
  run_once: true

