{
 "title": "JMX Dashboard (Basic)-v1.0.1",
 "description": "jmx exporter monitor",
 "tags": [
  "jmx",
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "env", "label": "Env", "query": { "query": "label_values(jvm_info, env)" } },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jvm_info{env=\"$env\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{env=\"$env\",job=\"$job\"}, instance)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(up{env=\"$env\",job=\"$job\"}, instance)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{env=\"$env\", job=\"$job\", instance=\"$instance\"}, area)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{env=\"$env\", job=\"$job\", instance=\"$instance\"}, pool)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_info{env=\"$env\", job=\"$job\", instance=\"$instance\"}, application)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JDK",
   "type": "stat",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_join(jvm_info{job=\"$job\", instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 20, "x": 2, "y": 3 },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_runtime_uptime{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_runtime_starttime{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Start time"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_availableprocessors{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalphysicalmemorysize{job=\"$job\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total RAM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalswapspacesize{job=\"$job\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total SWAP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Open FDs"
    }
   ]
  },
  {
   "title": "Cpu Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_processcputime{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Process"
    },
    {
     "expr": "java_lang_threading_currentthreadcputime{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Current Thread"
    },
    {
     "expr": "process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Total Spent"
    }
   ]
  },
  {
   "title": "CPU System load average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{job=\"$job\", instance=\"$instance\"} * 100",
     "legendFormat": "CPU System load average"
    }
   ]
  },
  {
   "title": "CPU Process Load (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_operatingsystem_processcpuload{job=\"$job\", instance=\"$instance\"}[1m]) * 100",
     "legendFormat": "CPU Process Load (1m avg)"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_operatingsystem_systemcpuload{job=\"$job\", instance=\"$instance\"}[1m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU System Load (1m avg)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (100 * java_lang_operatingsystem_freephysicalmemorysize{job=\"$job\", instance=\"$instance\"} / on(instance) java_lang_operatingsystem_totalphysicalmemorysize{job=\"$job\", instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Memory Utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SWAP Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (java_lang_operatingsystem_freeswapspacesize{job=\"$job\", instance=\"$instance\"} / on(instance) java_lang_operatingsystem_totalswapspacesize{job=\"$job\", instance=\"$instance\"} * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "SWAP Utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Descriptors"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ],
   "panels": [
    {
     "title": "Physical memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_operatingsystem_freephysicalmemorysize{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "java_lang_operatingsystem_totalphysicalmemorysize{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "java_lang_operatingsystem_committedvirtualmemorysize{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Committed VM"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Virtual"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Used [$memarea]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "repeat": "memarea",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=~\"$memarea\",job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area=~\"$memarea\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Memory Usage [$memarea]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "repeat": "memarea",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\", instance=\"$instance\"} / ignoring(area) group_left java_lang_operatingsystem_totalphysicalmemorysize{job=\"$job\", instance=\"$instance\"} *100",
       "legendFormat": "System"
      },
      {
       "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\", instance=\"$instance\"} / (jvm_memory_bytes_max{area=\"$memarea\", job=\"$job\",instance=\"$instance\"} >=0) *100",
       "legendFormat": "JVM"
      }
     ]
    },
    {
     "title": "JVM Memory committed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_committed{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{area}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory JVM Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory pool [$mempool]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "repeat": "mempool",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{pool=~\"$mempool\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=~\"$mempool\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=~\"$mempool\",job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "rate(jvm_memory_pool_bytes_committed{pool=~\"$mempool\",job=\"$job\",instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Committed Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC count rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC Time increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC Time rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threading Threads",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "java_lang_threading_threadcount{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "java_lang_threading_daemonthreadcount{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "java_lang_threading_peakthreadcount{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "java_lang_threading_totalstartedthreadcount{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 6 },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "jvm_threads_daemon{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_deadlocked{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "jvm_threads_peak{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "jvm_threads_started_total{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Started Total"
      }
     ]
    },
    {
     "title": "JVM Threading Threads increase",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(java_lang_threading_threadcount{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "increase(java_lang_threading_daemonthreadcount{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "increase(java_lang_threading_peakthreadcount{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "increase(java_lang_threading_totalstartedthreadcount{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current increase",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 17 },
     "targets": [
      {
       "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "increase(jvm_threads_daemon{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "increase(jvm_threads_deadlocked{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "increase(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "increase(jvm_threads_peak{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "increase(jvm_threads_started_total{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Started Total"
      }
     ]
    },
    {
     "title": "JVM Threading Threads rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(java_lang_threading_threadcount{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "rate(java_lang_threading_daemonthreadcount{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "rate(java_lang_threading_peakthreadcount{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "rate(java_lang_threading_totalstartedthreadcount{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 28 },
     "targets": [
      {
       "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "rate(jvm_threads_daemon{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "rate(jvm_threads_deadlocked{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "rate(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "rate(jvm_threads_peak{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "rate(jvm_threads_started_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Started Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Class Loading count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "java_lang_classloading_loadedclasscount{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "loaded"
      },
      {
       "expr": "java_lang_classloading_unloadedclasscount{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_currently_loaded {job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "currently"
      },
      {
       "expr": "jvm_classes_loaded_total{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Class Loading count increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(java_lang_classloading_loadedclasscount{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "loaded"
      },
      {
       "expr": "increase(java_lang_classloading_unloadedclasscount{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_classes_currently_loaded {job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "currently"
      },
      {
       "expr": "increase(jvm_classes_loaded_total{job=\"$job\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Class Loading count rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(java_lang_classloading_loadedclasscount{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "loaded"
      },
      {
       "expr": "rate(java_lang_classloading_unloadedclasscount{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_classes_currently_loaded {job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "currently"
      },
      {
       "expr": "rate(jvm_classes_loaded_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}