---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ./vars-common.yml
    - ./vars-{{ inventory_hostname }}.yml
    - ./vars_sftp.yml

  tasks:

    - name: Centos 7
      set_fact:
        OS: "C7"
        FAMALY: "RH"
      when: hostvars[inventory_hostname].ansible_distribution_major_version|int == 7
      tags: always
    
    - name: Centos 8
      set_fact:
        OS: "C8"
        FAMALY: "RH"
      when: hostvars[inventory_hostname].ansible_distribution_major_version|int == 8 and hostvars[inventory_hostname].ansible_distribution != "OracleLinux"
      tags: always
    
    - name: Oracle Linux  8
      set_fact:
        OS: "OLE8"
        FAMALY: "RH"
      when: hostvars[inventory_hostname].ansible_distribution_major_version|int == 8 and hostvars[inventory_hostname].ansible_distribution == "OracleLinux"
      tags: always
    
    - name: Fedora 32
      set_fact:
        OS: "OLE8"
        FAMALY: "RH"
      when: hostvars[inventory_hostname].ansible_distribution_major_version|int == 32 and hostvars[inventory_hostname].ansible_distribution == "Fedora"
      tags: always

    - name: debian 11
      set_fact:
        OS: "D11"
        FAMALY: "DEB"
      when: hostvars[inventory_hostname].ansible_distribution_major_version|int == 11
      tags: always
    
    - name: Debian 10
      set_fact:
        OS: "D10"
        FAMALY: "DEB"
      when: hostvars[inventory_hostname].ansible_distribution_major_version|int == 10 and hostvars[inventory_hostname].ansible_distribution != "Astra Linux"
      tags: always
    
    - name: Astra
      set_fact:
        OS: "AL"
        FAMALY: "DEB"
      when: hostvars[inventory_hostname].ansible_distribution_major_version|int == 1 and hostvars[inventory_hostname].ansible_distribution == "Astra Linux"
      tags: always
    
    - name: UBUNTU
      set_fact:
        OS: "UB"
        FAMALY: "DEB"
      when: hostvars[inventory_hostname].ansible_distribution == "Ubuntu"
      tags: always

    - name: RH - block
      block:
        - name: RH - upgrade all packages
          yum:
            name: '*'
            state: latest
            update_cache: yes
          when: update_all_packets is defined

    #    - name: sysbench - List sysbench  packages and register result
    #      yum:
    #        list: sysbench
    #      register: result_sysbench
    #      tags: install_sb
    #      when: install_sysbench is defined

        - name: sysbench - Install sysbench repo
          shell: curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh | sudo bash
#            args:
#            warn: false # set warn=false to prevent warning
          tags: install_sb
          when: install_sysbench is defined
    #      when: install_sysbench is defined and result_sysbench.changed
 
        - name: sysbench - install sysbench
          yum:
            name: sysbench
            state: latest
          tags: install_sb
          when: install_sysbench is defined
    #      when: install_sysbench is defined and result_sysbench.changed
  
        - name: sysbench - make dir
          file:
            path: "{{ item.path }}"
            state: directory
            mode: "{{ item.mode }}"
            owner: "{{ item.user }}"
            group: "{{ item.group }}"
          with_items:
            - { path: '/opt/sysbench', group: 'root', user: 'root', mode: '744' }
          tags: install_sb
          when: install_sysbench is defined
  
        - name: sysbench - copy script
          copy:
            src: ./template/sb.sh
            dest: /opt/sysbench/sb.sh
            owner: root
            group: root
            mode: 0700
          tags: 
            - install_sb_script
            - install_sb
          when: install_sysbench is defined
  
        - name: sysbench - add cron task
          cron:
            name: "run sysbench"
            minute: "*/15"
            job: "/opt/sysbench/sb.sh"
          notify: restart crond
          tags: install_sb
          when: install_sysbench is defined
  
        - name: sysbench - rotate logs
          copy:
            src: ./template/sysbench-logrotate.j2
            dest: /etc/logrotate.d/sysbench-logrotate
            owner: root
            group: wheel
            mode: 0644
          tags: install_sb
          when: install_sysbench is defined

      when: FAMALY == "RH"

#    - include: rh.yml
#      when: FAMALY == "RH"

    - name: rh -  rh.yml
      ansible.builtin.include_tasks: "rh.yml"
      when: FAMALY == "RH"

#    - include: java-rh.yml
    - name: rh - java-rh.yml
      ansible.builtin.include_tasks: "java-rh.yml"
      when: java_version is defined and FAMALY == "RH"

#    - include: docker-rh.yml
    - name: rh - docker-rh.yml
      ansible.builtin.include_tasks: "docker-rh.yml"
      when: FAMALY == "RH"

#    - include: ansible.yml
    - name: rh - ansible.yml
      ansible.builtin.include_tasks: "ansible.yml"
      when: FAMALY == "RH"


      # ---------------------------------------------------------
#    - name: DEB Block
#      block:
    - name: deb.yml
      ansible.builtin.include_tasks: "deb.yml"
      when: FAMALY == "DEB"

    - name: java-deb.yml
      ansible.builtin.include_tasks: "java-deb.yml"
      when: install_java | bool and FAMALY == "DEB"

    - name: docker-deb.yml
      ansible.builtin.include_tasks: " docker-deb.yml"
      when: FAMALY == "DEB"



#    - include: sftp.yml

#    - include: haproxy.yml

#    - include: keepalived.yml

#    - include: prometheus.yml

    - include: x11.yml

  handlers:
    - include: handlers.yml
